-- SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
-- SPDX-License-Identifier: MIT
-- Generated by scripts/gen_constants.py from constants/constants.json; edit the table, not this file.
-- Exact constants on unnormalised rationals: each derived constant's defining equation holds by `refl`
-- (cross-multiplication of integers, no normalisation). Twin of Lean/Constants/SI.lean.

{-# OPTIONS --without-K --safe #-}

module Constants.SI where

open import Data.Integer using (+_; -[1+_])
open import Data.Rational.Unnormalised.Base using (ℚᵘ; mkℚᵘ; _*_; _+_; _-_; _≃_; *≡*; _≤_; *≤*)
open import Data.Product using (_×_; _,_)
open import Relation.Binary.PropositionalEquality using (refl)
open import Relation.Nullary.Decidable using (toWitness)
import Data.Integer.Properties as ℤ

private
  two : ℚᵘ
  two = mkℚᵘ (+ 2) 0

-- ΔνCs: caesium-133 hyperfine transition frequency [Hz], cited (SI2019)
caesiumHyperfineFrequency : ℚᵘ
caesiumHyperfineFrequency = (mkℚᵘ (+ 9192631770) 0)

-- c: speed of light in vacuum [m s⁻¹], cited (SI2019)
speedOfLight : ℚᵘ
speedOfLight = (mkℚᵘ (+ 299792458) 0)

-- h: Planck constant [J s], cited (SI2019)
planck : ℚᵘ
planck = (mkℚᵘ (+ 132521403) 199999999999999999999999999999999999999999)

-- e: elementary charge [C], cited (SI2019)
elementaryCharge : ℚᵘ
elementaryCharge = (mkℚᵘ (+ 801088317) 4999999999999999999999999999)

-- k_B: Boltzmann constant [J K⁻¹], cited (SI2019)
boltzmann : ℚᵘ
boltzmann = (mkℚᵘ (+ 1380649) 99999999999999999999999999999)

-- N_A: Avogadro constant [mol⁻¹], cited (SI2019)
avogadro : ℚᵘ
avogadro = (mkℚᵘ (+ 602214076000000000000000) 0)

-- K_cd: luminous efficacy of 540 THz radiation [lm W⁻¹], cited (SI2019)
luminousEfficacy : ℚᵘ
luminousEfficacy = (mkℚᵘ (+ 683) 0)

-- R: molar gas constant [J mol⁻¹ K⁻¹], derived: avogadro * boltzmann
gasConstant : ℚᵘ
gasConstant = (mkℚᵘ (+ 207861565453831) 24999999999999)

gasConstant-derivation : gasConstant ≃ avogadro * boltzmann
gasConstant-derivation = *≡* refl

-- F: Faraday constant [C mol⁻¹], derived: avogadro * elementaryCharge
faraday : ℚᵘ
faraday = (mkℚᵘ (+ 120606665154137523) 1249999999999)

faraday-derivation : faraday ≃ avogadro * elementaryCharge
faraday-derivation = *≡* refl

-- c²: mass–energy conversion factor [m² s⁻²], derived: speedOfLight * speedOfLight
speedOfLightSquared : ℚᵘ
speedOfLightSquared = (mkℚᵘ (+ 89875517873681764) 0)

speedOfLightSquared-derivation : speedOfLightSquared ≃ speedOfLight * speedOfLight
speedOfLightSquared-derivation = *≡* refl

-- K_J: Josephson constant [Hz V⁻¹], derived: 2 * elementaryCharge / planck
josephson : ℚᵘ
josephson = (mkℚᵘ (+ 21362355120000000000000) 44173800)

josephson-derivation : josephson * (planck) ≃ two * elementaryCharge
josephson-derivation = *≡* refl

-- R_K: von Klitzing constant [Ω], derived: planck / (elementaryCharge * elementaryCharge)
vonKlitzing : ℚᵘ
vonKlitzing = (mkℚᵘ (+ 5521725125000000000000) 213914163877964162)

vonKlitzing-derivation : vonKlitzing * (elementaryCharge * elementaryCharge) ≃ planck
vonKlitzing-derivation = *≡* refl

-- Φ₀: magnetic flux quantum [Wb], derived: planck / (2 * elementaryCharge)
fluxQuantum : ℚᵘ
fluxQuantum = (mkℚᵘ (+ 44173801) 21362355119999999999999)

fluxQuantum-derivation : fluxQuantum * (two * elementaryCharge) ≃ planck
fluxQuantum-derivation = *≡* refl

-- G₀: conductance quantum [S], derived: 2 * elementaryCharge * elementaryCharge / planck
conductanceQuantum : ℚᵘ
conductanceQuantum = (mkℚᵘ (+ 213914163877964163) 2760862562499999999999)

conductanceQuantum-derivation : conductanceQuantum * (planck) ≃ two * elementaryCharge * elementaryCharge
conductanceQuantum-derivation = *≡* refl

-- α: fine-structure constant [1], measured (CODATA2022)
fineStructure : ℚᵘ
fineStructure = (mkℚᵘ (+ 72973525643) 9999999999999)
fineStructureUncertainty : ℚᵘ
fineStructureUncertainty = (mkℚᵘ (+ 11) 9999999999999)

-- m_e: electron mass [kg], measured (CODATA2022)
electronMass : ℚᵘ
electronMass = (mkℚᵘ (+ 91093837139) 99999999999999999999999999999999999999999)
electronMassUncertainty : ℚᵘ
electronMassUncertainty = (mkℚᵘ (+ 7) 24999999999999999999999999999999999999999)

-- R∞: Rydberg constant [m^-1], derived: fineStructure * fineStructure * electronMass * speedOfLight / (2 * planck)
rydberg : ℚᵘ
rydberg = (mkℚᵘ (+ 10387530739584650529984309579749063654017) 946581449999999999999999999999999)

rydberg-derivation : rydberg * (two * planck) ≃ fineStructure * fineStructure * electronMass * speedOfLight
rydberg-derivation = *≡* refl

rydberg-within-CODATA2022 : ((mkℚᵘ (+ 5193765366686165780378999038591358188549) 473290724999999999999999999999999) ≤ rydberg) × (rydberg ≤ (mkℚᵘ (+ 5193765373010661107271000961408641811451) 473290724999999999999999999999999))
rydberg-within-CODATA2022 = *≤* (toWitness {a? = _ ℤ.≤? _} _) , *≤* (toWitness {a? = _ ℤ.≤? _} _)

-- E_h: Hartree energy [J], derived: fineStructure * fineStructure * electronMass * speedOfLight * speedOfLight
hartreeEnergy : ℚᵘ
hartreeEnergy = (mkℚᵘ (+ 10899361805397240985092496046210715856126763013251) 2499999999999999999999999999999999999999999999999999999999999999999)

hartreeEnergy-derivation : hartreeEnergy ≃ fineStructure * fineStructure * electronMass * speedOfLight * speedOfLight
hartreeEnergy-derivation = *≡* refl

hartreeEnergy-within-CODATA2022 : ((mkℚᵘ (+ 5449680899439437000597683175281290451162362572047) 1249999999999999999999999999999999999999999999999999999999999999999) ≤ hartreeEnergy) × (hartreeEnergy ≤ (mkℚᵘ (+ 5449680906075562999402316824718709548837637427953) 1249999999999999999999999999999999999999999999999999999999999999999))
hartreeEnergy-within-CODATA2022 = *≤* (toWitness {a? = _ ℤ.≤? _} _) , *≤* (toWitness {a? = _ ℤ.≤? _} _)

-- λ_C: Compton wavelength [m], derived: planck / (electronMass * speedOfLight)
comptonWavelength : ℚᵘ
comptonWavelength = (mkℚᵘ (+ 18931629) 7802641527014999331)

comptonWavelength-derivation : comptonWavelength * (electronMass * speedOfLight) ≃ planck
comptonWavelength-derivation = *≡* refl

comptonWavelength-within-CODATA2022 : ((mkℚᵘ (+ 121315511731) 49999999999999999999999) ≤ comptonWavelength) × (comptonWavelength ≤ (mkℚᵘ (+ 121315511807) 49999999999999999999999))
comptonWavelength-within-CODATA2022 = *≤* (toWitness {a? = _ ℤ.≤? _} _) , *≤* (toWitness {a? = _ ℤ.≤? _} _)

-- ε₀: vacuum electric permittivity [F m⁻¹], derived: elementaryCharge * elementaryCharge / (2 * fineStructure * planck * speedOfLight)
vacuumPermittivity : ℚᵘ
vacuumPermittivity = (mkℚᵘ (+ 213914163877964163) 24159659615848077226571442349)

vacuumPermittivity-derivation : vacuumPermittivity * (two * fineStructure * planck * speedOfLight) ≃ elementaryCharge * elementaryCharge
vacuumPermittivity-derivation = *≡* refl

vacuumPermittivity-within-CODATA2022 : ((mkℚᵘ (+ 44270939087) 4999999999999999999999) ≤ vacuumPermittivity) × (vacuumPermittivity ≤ (mkℚᵘ (+ 44270939101) 4999999999999999999999))
vacuumPermittivity-within-CODATA2022 = *≤* (toWitness {a? = _ ℤ.≤? _} _) , *≤* (toWitness {a? = _ ℤ.≤? _} _)

-- μ₀: vacuum magnetic permeability [N A⁻²], derived: 2 * fineStructure * planck / (elementaryCharge * elementaryCharge * speedOfLight)
vacuumPermeability : ℚᵘ
vacuumPermeability = (mkℚᵘ (+ 11512564285793853725) 9161407569998526923097521)

vacuumPermeability-derivation : vacuumPermeability * (elementaryCharge * elementaryCharge * speedOfLight) ≃ two * fineStructure * planck
vacuumPermeability-derivation = *≡* refl

vacuumPermeability-within-CODATA2022 : ((mkℚᵘ (+ 125663706107) 99999999999999999) ≤ vacuumPermeability) × (vacuumPermeability ≤ (mkℚᵘ (+ 125663706147) 99999999999999999))
vacuumPermeability-within-CODATA2022 = *≤* (toWitness {a? = _ ℤ.≤? _} _) , *≤* (toWitness {a? = _ ℤ.≤? _} _)

-- w_n: non-evaporable water at complete hydration (Powers' model) [kg per kg cement], cited (Bentz2009)
nonEvaporableWater : ℚᵘ
nonEvaporableWater = (mkℚᵘ (+ 23) 99)

-- w_cs: chemical shrinkage at complete hydration (Powers' model) [kg water per kg cement], cited (Bentz2009)
chemicalShrinkage : ℚᵘ
chemicalShrinkage = (mkℚᵘ (+ 8) 124)

-- w_g: gel water at complete hydration (Powers' model) [kg per kg cement], cited (Bentz2009)
gelWater : ℚᵘ
gelWater = (mkℚᵘ (+ 19) 99)

-- ρ_w: density of water assigned in Powers' model [kg m⁻³], cited (Bentz2009)
waterDensity : ℚᵘ
waterDensity = (mkℚᵘ (+ 1000) 0)

-- ρ_c: density of cement assigned in Powers' model [kg m⁻³], cited (Bentz2009)
cementDensity : ℚᵘ
cementDensity = (mkℚᵘ (+ 3150) 0)

-- (w/c)*: water-cement ratio at which sealed paste just hydrates completely [1], derived: nonEvaporableWater + gelWater
criticalWcSealed : ℚᵘ
criticalWcSealed = (mkℚᵘ (+ 21) 49)

criticalWcSealed-derivation : criticalWcSealed ≃ nonEvaporableWater + gelWater
criticalWcSealed-derivation = *≡* refl

-- (w/c)_s: water-cement ratio below which space limits complete hydration [1], derived: nonEvaporableWater + gelWater - chemicalShrinkage
criticalWcSpace : ℚᵘ
criticalWcSpace = (mkℚᵘ (+ 89) 249)

criticalWcSpace-derivation : criticalWcSpace ≃ nonEvaporableWater + gelWater - chemicalShrinkage
criticalWcSpace-derivation = *≡* refl

-- ρ_c/ρ_w: specific gravity of cement in Powers' model [1], derived: cementDensity / waterDensity
densityRatio : ℚᵘ
densityRatio = (mkℚᵘ (+ 63) 19)

densityRatio-derivation : densityRatio * (waterDensity) ≃ cementDensity
densityRatio-derivation = *≡* refl

-- v_cs: chemical-shrinkage volume per volume of cement reacted [1], derived: chemicalShrinkage * densityRatio
shrinkageVolume : ℚᵘ
shrinkageVolume = (mkℚᵘ (+ 126) 624)

shrinkageVolume-derivation : shrinkageVolume ≃ chemicalShrinkage * densityRatio
shrinkageVolume-derivation = *≡* refl

-- v_gw: gel-water volume per volume of cement reacted [1], derived: gelWater * densityRatio
gelWaterVolume : ℚᵘ
gelWaterVolume = (mkℚᵘ (+ 1197) 1999)

gelWaterVolume-derivation : gelWaterVolume ≃ gelWater * densityRatio
gelWaterVolume-derivation = *≡* refl

-- v_cw: capillary water consumed per volume of cement reacted [1], derived: criticalWcSealed * densityRatio
capillaryConsumption : ℚᵘ
capillaryConsumption = (mkℚᵘ (+ 1323) 999)

capillaryConsumption-derivation : capillaryConsumption ≃ criticalWcSealed * densityRatio
capillaryConsumption-derivation = *≡* refl

-- w_n − w_cs: water bound into gel solids per mass of cement reacted [kg per kg cement], derived: nonEvaporableWater - chemicalShrinkage
boundWater : ℚᵘ
boundWater = (mkℚᵘ (+ 83) 499)

boundWater-derivation : boundWater ≃ nonEvaporableWater - chemicalShrinkage
boundWater-derivation = *≡* refl

-- v_b: volume of water bound into gel solids per volume of cement reacted [1], derived: boundWater * densityRatio
boundWaterVolume : ℚᵘ
boundWaterVolume = (mkℚᵘ (+ 5229) 9999)

boundWaterVolume-derivation : boundWaterVolume ≃ boundWater * densityRatio
boundWaterVolume-derivation = *≡* refl

-- v_gs: gel-solids volume per volume of cement reacted [1], derived: 1 + boundWaterVolume
gelSolidsVolume : ℚᵘ
gelSolidsVolume = (mkℚᵘ (+ 15229) 9999)

gelSolidsVolume-derivation : gelSolidsVolume ≃ (mkℚᵘ (+ 1) 0) + boundWaterVolume
gelSolidsVolume-derivation = *≡* refl

-- A: intrinsic strength of the gel in Powers' gel-space law [MPa], cited (Powers1958)
powersGelStrength : ℚᵘ
powersGelStrength = (mkℚᵘ (+ 234) 0)

-- n: exponent of Powers' gel-space law [1], cited (Powers1958)
powersGelExponent : ℚᵘ
powersGelExponent = (mkℚᵘ (+ 3) 0)

-- Q_C3S: heat released by complete hydration of tricalcium silicate (alite) [J/g], measured (Taylor1997)
hydrationHeatC3S : ℚᵘ
hydrationHeatC3S = (mkℚᵘ (+ 517) 0)
hydrationHeatC3SUncertainty : ℚᵘ
hydrationHeatC3SUncertainty = (mkℚᵘ (+ 13) 0)

-- Q_C2S: heat released by complete hydration of dicalcium silicate (belite) [J/g], cited (Taylor1997)
hydrationHeatC2S : ℚᵘ
hydrationHeatC2S = (mkℚᵘ (+ 262) 0)

-- Q_C3A,AFm: heat released by complete hydration of tricalcium aluminate to AFm [J/g], cited (Taylor1997)
hydrationHeatC3AtoAFm : ℚᵘ
hydrationHeatC3AtoAFm = (mkℚᵘ (+ 1144) 0)

-- Q_C3A,AFt: heat released by complete hydration of tricalcium aluminate to AFt [J/g], cited (Taylor1997)
hydrationHeatC3AtoAFt : ℚᵘ
hydrationHeatC3AtoAFt = (mkℚᵘ (+ 1672) 0)

-- Q_C4AF: heat released by complete hydration of tetracalcium aluminoferrite [J/g], cited (Taylor1997)
hydrationHeatC4AF : ℚᵘ
hydrationHeatC4AF = (mkℚᵘ (+ 418) 0)

-- Q_hyd: heat of complete hydration of a portland cement (model default) [J/g], policy (a model choice, not a constant): a cement's heat of complete hydration is the mass-weighted sum of its phases' heats, so for a clinker of the four phases it lies between the least and the greatest phase heat; 450 is the gate's default for an unspecified portland cement
hydrationHeatDefault : ℚᵘ
hydrationHeatDefault = (mkℚᵘ (+ 450) 0)

hydrationHeatDefault-in-range : (hydrationHeatC2S ≤ hydrationHeatDefault) × (hydrationHeatDefault ≤ hydrationHeatC3AtoAFt)
hydrationHeatDefault-in-range = *≤* (toWitness {a? = _ ℤ.≤? _} _) , *≤* (toWitness {a? = _ ℤ.≤? _} _)
