-- SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
-- SPDX-License-Identifier: MIT
-- Generated by scripts/gen_constants.py from constants/constants.json; edit the table, not this file.
-- Exact constants on unnormalised rationals: each derived constant's defining equation holds by `refl`
-- (cross-multiplication of integers, no normalisation). Twin of Lean/Constants/SI.lean.

{-# OPTIONS --without-K --safe #-}

module Constants.SI where

open import Data.Integer using (+_; -[1+_])
open import Data.Rational.Unnormalised.Base using (ℚᵘ; mkℚᵘ; _*_; _≃_; *≡*; _≤_; *≤*)
open import Data.Product using (_×_; _,_)
open import Relation.Binary.PropositionalEquality using (refl)
open import Relation.Nullary.Decidable using (toWitness)
import Data.Integer.Properties as ℤ

private
  two : ℚᵘ
  two = mkℚᵘ (+ 2) 0

-- ΔνCs: caesium-133 hyperfine transition frequency [Hz], cited (SI2019)
caesiumHyperfineFrequency : ℚᵘ
caesiumHyperfineFrequency = (mkℚᵘ (+ 9192631770) 0)

-- c: speed of light in vacuum [m s⁻¹], cited (SI2019)
speedOfLight : ℚᵘ
speedOfLight = (mkℚᵘ (+ 299792458) 0)

-- h: Planck constant [J s], cited (SI2019)
planck : ℚᵘ
planck = (mkℚᵘ (+ 132521403) 199999999999999999999999999999999999999999)

-- e: elementary charge [C], cited (SI2019)
elementaryCharge : ℚᵘ
elementaryCharge = (mkℚᵘ (+ 801088317) 4999999999999999999999999999)

-- k_B: Boltzmann constant [J K⁻¹], cited (SI2019)
boltzmann : ℚᵘ
boltzmann = (mkℚᵘ (+ 1380649) 99999999999999999999999999999)

-- N_A: Avogadro constant [mol⁻¹], cited (SI2019)
avogadro : ℚᵘ
avogadro = (mkℚᵘ (+ 602214076000000000000000) 0)

-- K_cd: luminous efficacy of 540 THz radiation [lm W⁻¹], cited (SI2019)
luminousEfficacy : ℚᵘ
luminousEfficacy = (mkℚᵘ (+ 683) 0)

-- R: molar gas constant [J mol⁻¹ K⁻¹], derived: avogadro * boltzmann
gasConstant : ℚᵘ
gasConstant = (mkℚᵘ (+ 207861565453831) 24999999999999)

gasConstant-derivation : gasConstant ≃ avogadro * boltzmann
gasConstant-derivation = *≡* refl

-- F: Faraday constant [C mol⁻¹], derived: avogadro * elementaryCharge
faraday : ℚᵘ
faraday = (mkℚᵘ (+ 120606665154137523) 1249999999999)

faraday-derivation : faraday ≃ avogadro * elementaryCharge
faraday-derivation = *≡* refl

-- c²: mass–energy conversion factor [m² s⁻²], derived: speedOfLight * speedOfLight
speedOfLightSquared : ℚᵘ
speedOfLightSquared = (mkℚᵘ (+ 89875517873681764) 0)

speedOfLightSquared-derivation : speedOfLightSquared ≃ speedOfLight * speedOfLight
speedOfLightSquared-derivation = *≡* refl

-- K_J: Josephson constant [Hz V⁻¹], derived: 2 * elementaryCharge / planck
josephson : ℚᵘ
josephson = (mkℚᵘ (+ 21362355120000000000000) 44173800)

josephson-derivation : josephson * (planck) ≃ two * elementaryCharge
josephson-derivation = *≡* refl

-- R_K: von Klitzing constant [Ω], derived: planck / (elementaryCharge * elementaryCharge)
vonKlitzing : ℚᵘ
vonKlitzing = (mkℚᵘ (+ 5521725125000000000000) 213914163877964162)

vonKlitzing-derivation : vonKlitzing * (elementaryCharge * elementaryCharge) ≃ planck
vonKlitzing-derivation = *≡* refl

-- Φ₀: magnetic flux quantum [Wb], derived: planck / (2 * elementaryCharge)
fluxQuantum : ℚᵘ
fluxQuantum = (mkℚᵘ (+ 44173801) 21362355119999999999999)

fluxQuantum-derivation : fluxQuantum * (two * elementaryCharge) ≃ planck
fluxQuantum-derivation = *≡* refl

-- G₀: conductance quantum [S], derived: 2 * elementaryCharge * elementaryCharge / planck
conductanceQuantum : ℚᵘ
conductanceQuantum = (mkℚᵘ (+ 213914163877964163) 2760862562499999999999)

conductanceQuantum-derivation : conductanceQuantum * (planck) ≃ two * elementaryCharge * elementaryCharge
conductanceQuantum-derivation = *≡* refl

-- α: fine-structure constant [1], measured (CODATA2022)
fineStructure : ℚᵘ
fineStructure = (mkℚᵘ (+ 72973525643) 9999999999999)
fineStructureUncertainty : ℚᵘ
fineStructureUncertainty = (mkℚᵘ (+ 11) 9999999999999)

-- ε₀: vacuum electric permittivity [F m⁻¹], derived: elementaryCharge * elementaryCharge / (2 * fineStructure * planck * speedOfLight)
vacuumPermittivity : ℚᵘ
vacuumPermittivity = (mkℚᵘ (+ 213914163877964163) 24159659615848077226571442349)

vacuumPermittivity-derivation : vacuumPermittivity * (two * fineStructure * planck * speedOfLight) ≃ elementaryCharge * elementaryCharge
vacuumPermittivity-derivation = *≡* refl

vacuumPermittivity-within-CODATA2022 : ((mkℚᵘ (+ 44270939087) 4999999999999999999999) ≤ vacuumPermittivity) × (vacuumPermittivity ≤ (mkℚᵘ (+ 44270939101) 4999999999999999999999))
vacuumPermittivity-within-CODATA2022 = *≤* (toWitness {a? = _ ℤ.≤? _} _) , *≤* (toWitness {a? = _ ℤ.≤? _} _)

-- μ₀: vacuum magnetic permeability [N A⁻²], derived: 2 * fineStructure * planck / (elementaryCharge * elementaryCharge * speedOfLight)
vacuumPermeability : ℚᵘ
vacuumPermeability = (mkℚᵘ (+ 11512564285793853725) 9161407569998526923097521)

vacuumPermeability-derivation : vacuumPermeability * (elementaryCharge * elementaryCharge * speedOfLight) ≃ two * fineStructure * planck
vacuumPermeability-derivation = *≡* refl

vacuumPermeability-within-CODATA2022 : ((mkℚᵘ (+ 125663706107) 99999999999999999) ≤ vacuumPermeability) × (vacuumPermeability ≤ (mkℚᵘ (+ 125663706147) 99999999999999999))
vacuumPermeability-within-CODATA2022 = *≤* (toWitness {a? = _ ℤ.≤? _} _) , *≤* (toWitness {a? = _ ℤ.≤? _} _)
