(* SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar *)
(* SPDX-License-Identifier: MIT *)
(* Generated by scripts/gen_constants.py from constants/constants.json; edit the table, not this file. *)
(* Exact rational constants; each derived constant's value and defining equation are proved by        *)
(* computation (twin of Lean/Constants/SI.lean). Zero Axiom, Parameter or Admitted.                  *)

From Stdlib Require Import QArith.
Open Scope Q_scope.

(* ΔνCs: caesium-133 hyperfine transition frequency [Hz], cited (SI2019) *)
Definition caesiumHyperfineFrequency : Q := (Qmake 9192631770 1).

(* c: speed of light in vacuum [m s⁻¹], cited (SI2019) *)
Definition speedOfLight : Q := (Qmake 299792458 1).

(* h: Planck constant [J s], cited (SI2019) *)
Definition planck : Q := (Qmake 132521403 200000000000000000000000000000000000000000).

(* e: elementary charge [C], cited (SI2019) *)
Definition elementaryCharge : Q := (Qmake 801088317 5000000000000000000000000000).

(* k_B: Boltzmann constant [J K⁻¹], cited (SI2019) *)
Definition boltzmann : Q := (Qmake 1380649 100000000000000000000000000000).

(* N_A: Avogadro constant [mol⁻¹], cited (SI2019) *)
Definition avogadro : Q := (Qmake 602214076000000000000000 1).

(* K_cd: luminous efficacy of 540 THz radiation [lm W⁻¹], cited (SI2019) *)
Definition luminousEfficacy : Q := (Qmake 683 1).

(* R: molar gas constant [J mol⁻¹ K⁻¹], derived: avogadro * boltzmann *)
Definition gasConstant : Q := avogadro * boltzmann.
Lemma gasConstant_value : gasConstant == (Qmake 207861565453831 25000000000000).
Proof. vm_compute. reflexivity. Qed.

(* F: Faraday constant [C mol⁻¹], derived: avogadro * elementaryCharge *)
Definition faraday : Q := avogadro * elementaryCharge.
Lemma faraday_value : faraday == (Qmake 120606665154137523 1250000000000).
Proof. vm_compute. reflexivity. Qed.

(* c²: mass–energy conversion factor [m² s⁻²], derived: speedOfLight * speedOfLight *)
Definition speedOfLightSquared : Q := speedOfLight * speedOfLight.
Lemma speedOfLightSquared_value : speedOfLightSquared == (Qmake 89875517873681764 1).
Proof. vm_compute. reflexivity. Qed.

(* K_J: Josephson constant [Hz V⁻¹], derived: 2 * elementaryCharge / planck *)
Definition josephson : Q := 2 * elementaryCharge / planck.
Lemma josephson_value : josephson == (Qmake 21362355120000000000000 44173801).
Proof. vm_compute. reflexivity. Qed.
Lemma josephson_derivation : (Qmake 21362355120000000000000 44173801) * (planck) == 2 * elementaryCharge.
Proof. vm_compute. reflexivity. Qed.

(* R_K: von Klitzing constant [Ω], derived: planck / (elementaryCharge * elementaryCharge) *)
Definition vonKlitzing : Q := planck / (elementaryCharge * elementaryCharge).
Lemma vonKlitzing_value : vonKlitzing == (Qmake 5521725125000000000000 213914163877964163).
Proof. vm_compute. reflexivity. Qed.
Lemma vonKlitzing_derivation : (Qmake 5521725125000000000000 213914163877964163) * (elementaryCharge * elementaryCharge) == planck.
Proof. vm_compute. reflexivity. Qed.

(* Φ₀: magnetic flux quantum [Wb], derived: planck / (2 * elementaryCharge) *)
Definition fluxQuantum : Q := planck / (2 * elementaryCharge).
Lemma fluxQuantum_value : fluxQuantum == (Qmake 44173801 21362355120000000000000).
Proof. vm_compute. reflexivity. Qed.
Lemma fluxQuantum_derivation : (Qmake 44173801 21362355120000000000000) * (2 * elementaryCharge) == planck.
Proof. vm_compute. reflexivity. Qed.

(* G₀: conductance quantum [S], derived: 2 * elementaryCharge * elementaryCharge / planck *)
Definition conductanceQuantum : Q := 2 * elementaryCharge * elementaryCharge / planck.
Lemma conductanceQuantum_value : conductanceQuantum == (Qmake 213914163877964163 2760862562500000000000).
Proof. vm_compute. reflexivity. Qed.
Lemma conductanceQuantum_derivation : (Qmake 213914163877964163 2760862562500000000000) * (planck) == 2 * elementaryCharge * elementaryCharge.
Proof. vm_compute. reflexivity. Qed.

(* α: fine-structure constant [1], measured (CODATA2022) *)
Definition fineStructure : Q := (Qmake 72973525643 10000000000000).
Definition fineStructureUncertainty : Q := (Qmake 11 10000000000000).

(* ε₀: vacuum electric permittivity [F m⁻¹], derived: elementaryCharge * elementaryCharge / (2 * fineStructure * planck * speedOfLight) *)
Definition vacuumPermittivity : Q := elementaryCharge * elementaryCharge / (2 * fineStructure * planck * speedOfLight).
Lemma vacuumPermittivity_value : vacuumPermittivity == (Qmake 213914163877964163 24159659615848077226571442350).
Proof. vm_compute. reflexivity. Qed.
Lemma vacuumPermittivity_derivation : (Qmake 213914163877964163 24159659615848077226571442350) * (2 * fineStructure * planck * speedOfLight) == elementaryCharge * elementaryCharge.
Proof. vm_compute. reflexivity. Qed.
Lemma vacuumPermittivity_within_CODATA2022 :
  (Qmake 44270939087 5000000000000000000000) <= vacuumPermittivity /\ vacuumPermittivity <= (Qmake 44270939101 5000000000000000000000).
Proof. split; vm_compute; discriminate. Qed.

(* μ₀: vacuum magnetic permeability [N A⁻²], derived: 2 * fineStructure * planck / (elementaryCharge * elementaryCharge * speedOfLight) *)
Definition vacuumPermeability : Q := 2 * fineStructure * planck / (elementaryCharge * elementaryCharge * speedOfLight).
Lemma vacuumPermeability_value : vacuumPermeability == (Qmake 11512564285793853725 9161407569998526923097522).
Proof. vm_compute. reflexivity. Qed.
Lemma vacuumPermeability_derivation : (Qmake 11512564285793853725 9161407569998526923097522) * (elementaryCharge * elementaryCharge * speedOfLight) == 2 * fineStructure * planck.
Proof. vm_compute. reflexivity. Qed.
Lemma vacuumPermeability_within_CODATA2022 :
  (Qmake 125663706107 100000000000000000) <= vacuumPermeability /\ vacuumPermeability <= (Qmake 125663706147 100000000000000000).
Proof. split; vm_compute; discriminate. Qed.

(* w_n: non-evaporable water at complete hydration (Powers' model) [kg per kg cement], cited (Bentz2009) *)
Definition nonEvaporableWater : Q := (Qmake 23 100).

(* w_cs: chemical shrinkage at complete hydration (Powers' model) [kg water per kg cement], cited (Bentz2009) *)
Definition chemicalShrinkage : Q := (Qmake 8 125).

(* w_g: gel water at complete hydration (Powers' model) [kg per kg cement], cited (Bentz2009) *)
Definition gelWater : Q := (Qmake 19 100).

(* ρ_w: density of water assigned in Powers' model [kg m⁻³], cited (Bentz2009) *)
Definition waterDensity : Q := (Qmake 1000 1).

(* ρ_c: density of cement assigned in Powers' model [kg m⁻³], cited (Bentz2009) *)
Definition cementDensity : Q := (Qmake 3150 1).

(* (w/c)*: water-cement ratio at which sealed paste just hydrates completely [1], derived: nonEvaporableWater + gelWater *)
Definition criticalWcSealed : Q := nonEvaporableWater + gelWater.
Lemma criticalWcSealed_value : criticalWcSealed == (Qmake 21 50).
Proof. vm_compute. reflexivity. Qed.

(* (w/c)_s: water-cement ratio below which space limits complete hydration [1], derived: nonEvaporableWater + gelWater - chemicalShrinkage *)
Definition criticalWcSpace : Q := nonEvaporableWater + gelWater - chemicalShrinkage.
Lemma criticalWcSpace_value : criticalWcSpace == (Qmake 89 250).
Proof. vm_compute. reflexivity. Qed.

(* ρ_c/ρ_w: specific gravity of cement in Powers' model [1], derived: cementDensity / waterDensity *)
Definition densityRatio : Q := cementDensity / waterDensity.
Lemma densityRatio_value : densityRatio == (Qmake 63 20).
Proof. vm_compute. reflexivity. Qed.
Lemma densityRatio_derivation : (Qmake 63 20) * (waterDensity) == cementDensity.
Proof. vm_compute. reflexivity. Qed.

(* v_cs: chemical-shrinkage volume per volume of cement reacted [1], derived: chemicalShrinkage * densityRatio *)
Definition shrinkageVolume : Q := chemicalShrinkage * densityRatio.
Lemma shrinkageVolume_value : shrinkageVolume == (Qmake 126 625).
Proof. vm_compute. reflexivity. Qed.

(* v_gw: gel-water volume per volume of cement reacted [1], derived: gelWater * densityRatio *)
Definition gelWaterVolume : Q := gelWater * densityRatio.
Lemma gelWaterVolume_value : gelWaterVolume == (Qmake 1197 2000).
Proof. vm_compute. reflexivity. Qed.

(* v_cw: capillary water consumed per volume of cement reacted [1], derived: criticalWcSealed * densityRatio *)
Definition capillaryConsumption : Q := criticalWcSealed * densityRatio.
Lemma capillaryConsumption_value : capillaryConsumption == (Qmake 1323 1000).
Proof. vm_compute. reflexivity. Qed.

(* w_n − w_cs: water bound into gel solids per mass of cement reacted [kg per kg cement], derived: nonEvaporableWater - chemicalShrinkage *)
Definition boundWater : Q := nonEvaporableWater - chemicalShrinkage.
Lemma boundWater_value : boundWater == (Qmake 83 500).
Proof. vm_compute. reflexivity. Qed.

(* v_b: volume of water bound into gel solids per volume of cement reacted [1], derived: boundWater * densityRatio *)
Definition boundWaterVolume : Q := boundWater * densityRatio.
Lemma boundWaterVolume_value : boundWaterVolume == (Qmake 5229 10000).
Proof. vm_compute. reflexivity. Qed.

(* v_gs: gel-solids volume per volume of cement reacted [1], derived: 1 + boundWaterVolume *)
Definition gelSolidsVolume : Q := 1 + boundWaterVolume.
Lemma gelSolidsVolume_value : gelSolidsVolume == (Qmake 15229 10000).
Proof. vm_compute. reflexivity. Qed.

(* A: intrinsic strength of the gel in Powers' gel-space law [MPa], cited (Powers1958) *)
Definition powersGelStrength : Q := (Qmake 234 1).

(* n: exponent of Powers' gel-space law [1], cited (Powers1958) *)
Definition powersGelExponent : Q := (Qmake 3 1).
