#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
# SPDX-License-Identifier: MIT
"""Generate the ground-state modules from chemistry/ground_states.json (cited NIST ASD data), in four languages.

Each NIST configuration lists the valence subshells; the full occupancy is the noble-gas core followed by the
period's omitted subshells filled completely, in Madelung order, until the electron count equals Z. A partial fill,
an unknown subshell or a count that does not reach Z is an error: the data, not this script, decides every
occupancy.

Every language receives the cited occupancies, the Madelung order (subshells by n + ℓ, then n), the computed Madelung
configuration of any Z, and the same theorems, decided by computation:

  madelung order     sorted by (n + ℓ, n) and complete up to 7p
  electron count     every computed configuration for Z ≤ 118 holds exactly Z electrons; every cited one holds its Z
  capacity           no subshell holds more than 2(2ℓ + 1) electrons, computed or cited
  exceptions         the elements whose cited ground state differs from the Madelung prediction are exactly the
                     computed list (twenty: Cr … Lr)

`--check` regenerates in memory and fails on any difference.
"""
from __future__ import annotations

import json
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SPDX = "SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar"
HEADER = "Generated by scripts/gen_ground_states.py from chemistry/ground_states.json; edit the data, not this file."
LETTERS = "spdf"
ORDER = sorted(((n, l) for n in range(1, 8) for l in range(0, min(n, 4))), key=lambda s: (s[0] + s[1], s[0]))
NOBLE = [2, 10, 18, 36, 54, 86]
ZMAX = 118


def capacity(s: tuple[int, int]) -> int:
    return 2 * (2 * s[1] + 1)


def madelung(z: int) -> list[tuple[int, int, int]]:
    out, left = [], z
    for s in ORDER:
        if left <= 0:
            break
        k = min(capacity(s), left)
        out.append((s[0], s[1], k))
        left -= k
    return out


def expand(z: int, config: str) -> list[tuple[int, int, int]]:
    listed: dict[tuple[int, int], int] = {}
    for part in config.split("."):
        if part.startswith("("):
            continue  # an intermediate coupling term, not an occupancy
        m = re.fullmatch(r"(\d)([spdf])(\d*)", part)
        if not m:
            raise SystemExit(f"Z={z}: cannot read subshell {part!r} in {config!r}")
        listed[(int(m.group(1)), LETTERS.index(m.group(2)))] = int(m.group(3) or 1)
    core = max((g for g in NOBLE if g < z), default=0)
    occ = {(n, l): k for n, l, k in madelung(core)}
    occ.update(listed)
    deficit = z - sum(occ.values())
    for s in ORDER:
        if deficit <= 0:
            break
        if s in occ:
            continue
        if capacity(s) > deficit:
            raise SystemExit(f"Z={z}: {config!r} would need a partial fill of {s}")
        occ[s] = capacity(s)
        deficit -= capacity(s)
    if deficit != 0:
        raise SystemExit(f"Z={z}: {config!r} leaves {deficit} electrons unplaced")
    return [(n, l, occ[(n, l)]) for n, l in ORDER if occ.get((n, l), 0) > 0]


def load():
    with open(os.path.join(ROOT, "chemistry/ground_states.json"), encoding="utf-8") as f:
        doc = json.load(f)
    atoms = [(a["z"], a["symbol"], expand(a["z"], a["nist_configuration"])) for a in doc["atoms"]]
    exceptions = [z for z, _, occ in atoms if occ != madelung(z)]
    return doc, atoms, exceptions


def triples(occ, fmt):
    return ", ".join(fmt.format(n=n, l=l, k=k) for n, l, k in occ)


# --------------------------------------------------------------------------------------------------- Lean

def lean(doc, atoms, exceptions) -> str:
    src = doc["source"]
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", "/-", f"  {HEADER}", "",
         "  Ground-state electron configurations of the neutral atoms Z = 1 … 103, cited from the NIST Atomic Spectra",
         f"  Database ({src['retrieved']}; SHA-256 of the response {src['sha256_of_response']}), and the Madelung",
         "  (n + ℓ, then n) prediction, computed. A configuration is a list of (n, ℓ, occupancy) in Madelung order.",
         "  `madelungRank` composes with `ElementElectronic.madelungPriority` (`madelungRank_priority`).", "-/", "",
         "import ElementElectronic", "", "namespace UMST.Chem.GroundStates", "",
         "/-- Electrons a subshell (n, ℓ) holds when full: 2(2ℓ + 1). -/",
         "def capacity (s : Nat × Nat)  : Nat := 2 * (2 * s.2 + 1)", "",
         "/-- Madelung rank: subshells fill by n + ℓ, then by n (n ≤ 7 < 8). -/",
         "def madelungRank (s : Nat × Nat)  : Nat := (s.1 + s.2) * 8 + s.1", "",
         "/-- The rank is the cell's Madelung priority, refined by n. -/",
         "theorem madelungRank_priority (q : UMST.Chem.QLatticeCell) :",
         "    madelungRank (q.nQ, q.ell) = UMST.Chem.madelungPriority q * 8 + q.nQ := rfl", "",
         "/-- Subshells 1s … 7p in Madelung order. -/",
         "def madelungOrder : List (Nat × Nat) :=",
         "  [" + ", ".join(f"({n}, {l})" for n, l in ORDER) + "]", "",
         "theorem madelungOrder_sorted : madelungOrder.Pairwise (fun a b => madelungRank a < madelungRank b) := by",
         "  decide", "",
         "/-- Every subshell with 1 ≤ n ≤ 7 and ℓ < min(n, 4) appears. -/",
         "theorem madelungOrder_complete :",
         "    ((List.range 8).all fun n => (List.range 4).all fun l =>",
         "      !(1 ≤ n && l < n) || madelungOrder.contains (n, l)) = true := by",
         "  decide", "",
         "/-- Fill subshells in order until `z` electrons are placed. -/",
         "def fill : List (Nat × Nat) → Nat → List (Nat × Nat × Nat)",
         "  | [], _ => []",
         "  | _, 0 => []",
         "  | s :: rest, z + 1 =>",
         "    let k := min (capacity s) (z + 1)",
         "    (s.1, s.2, k) :: fill rest (z + 1 - k)", "",
         "/-- The Madelung prediction for `z` electrons. -/",
         "def madelung (z   : Nat) : List (Nat × Nat × Nat) := fill madelungOrder z", "",
         "/-- Electrons in a configuration. -/",
         "def electrons (c : List (Nat × Nat × Nat))  : Nat := (c.map fun x => x.2.2).sum", "",
         "/-- No subshell above its capacity. -/",
         "def withinCapacity (c : List (Nat × Nat × Nat)) : Bool := c.all fun x => x.2.2 ≤ capacity (x.1, x.2.1)", "",
         "set_option maxHeartbeats 4000000 in",
         "/-- Cited ground states (NIST ASD), expanded to full occupancies. -/",
         "def observed : List (Nat × List (Nat × Nat × Nat)) := ["]
    L += [f"  ({z}, [{triples(occ, '({n}, {l}, {k})')}])" + ("," if i < len(atoms) - 1 else "")
          for i, (z, _, occ) in enumerate(atoms)]
    L += ["]", "",
          f"theorem madelung_electrons_check : (List.range {ZMAX + 1}).all (fun z => electrons (madelung z) == z) = true := by",
          "  decide", "",
          f"/-- Every Madelung configuration for Z ≤ {ZMAX} holds exactly Z electrons. -/",
          f"theorem madelung_electrons (z : Nat) (hz : z ≤ {ZMAX}) : electrons (madelung z) = z := by",
          "  have h := List.all_eq_true.mp madelung_electrons_check z (List.mem_range.mpr (by omega))",
          "  simpa using h", "",
          f"theorem madelung_withinCapacity_check : (List.range {ZMAX + 1}).all (fun z => withinCapacity (madelung z)) = true := by",
          "  decide", "",
          f"/-- No Madelung configuration for Z ≤ {ZMAX} puts more than 2(2ℓ + 1) electrons in a subshell. -/",
          f"theorem madelung_withinCapacity (z : Nat) (hz : z ≤ {ZMAX}) : withinCapacity (madelung z) = true :=",
          "  List.all_eq_true.mp madelung_withinCapacity_check z (List.mem_range.mpr (by omega))", "",
          "theorem observed_atomic_numbers : observed.map Prod.fst = List.range' 1 " + str(len(atoms)) + " := by",
          "  decide", "",
          "theorem observed_electrons : observed.all (fun e => electrons e.2 == e.1) = true := by",
          "  decide", "",
          "theorem observed_withinCapacity : observed.all (fun e => withinCapacity e.2) = true := by",
          "  decide", "",
          "/-- The elements whose cited ground state differs from the Madelung prediction. -/",
          "theorem madelung_exceptions :",
          "    (observed.filter fun e => e.2 != madelung e.1).map Prod.fst =",
          "      [" + ", ".join(map(str, exceptions)) + "] := by",
          "  decide", "",
          "end UMST.Chem.GroundStates", ""]
    return "\n".join(L)


# --------------------------------------------------------------------------------------------------- Coq

def coq(doc, atoms, exceptions) -> str:
    src = doc["source"]
    L = [f"(* {SPDX} *)", "(* SPDX-License-Identifier: MIT *)", f"(* {HEADER} *)",
         "(* Ground states Z = 1 … 103 cited from the NIST Atomic Spectra Database                              *)",
         f"(* ({src['retrieved']}; SHA-256 {src['sha256_of_response'][:32]}…), the Madelung prediction computed;       *)",
         "(* twin of Lean/Chem/GroundStates.lean. Zero Axiom, Parameter or Admitted.                              *)", "",
         "From Stdlib Require Import List Arith Lia Bool.", "Import ListNotations.", "",
         "Definition capacity (s : nat * nat) : nat := 2 * (2 * snd s + 1).",
         "Definition madelungRank (s : nat * nat) : nat := (fst s + snd s) * 8 + fst s.", "",
         "Definition madelungOrder : list (nat * nat) :=",
         "  [" + "; ".join(f"({n}, {l})" for n, l in ORDER) + "].", "",
         "Fixpoint sortedB (l : list (nat * nat)) : bool :=",
         "  match l with",
         "  | a :: ((b :: _) as rest) => Nat.ltb (madelungRank a) (madelungRank b) && sortedB rest",
         "  | _ => true",
         "  end.",
         "Lemma madelungOrder_sorted : sortedB madelungOrder = true.",
         "Proof. vm_compute. reflexivity. Qed.", "",
         "Fixpoint fill (order : list (nat * nat)) (z : nat) : list (nat * nat * nat) :=",
         "  match order, z with",
         "  | [], _ => []",
         "  | _, 0 => []",
         "  | s :: rest, S z' => let k := Nat.min (capacity s) z in (fst s, snd s, k) :: fill rest (z - k)",
         "  end.",
         "Definition madelung (z : nat) : list (nat * nat * nat) := fill madelungOrder z.",
         "Definition electrons (c : list (nat * nat * nat)) : nat := fold_right (fun x acc => snd x + acc) 0 c.",
         "Definition withinCapacity (c : list (nat * nat * nat)) : bool :=",
         "  forallb (fun x => Nat.leb (snd x) (capacity (fst (fst x), snd (fst x)))) c.",
         "Fixpoint configEqb (a b : list (nat * nat * nat)) : bool :=",
         "  match a, b with",
         "  | [], [] => true",
         "  | (n1, l1, k1) :: r1, (n2, l2, k2) :: r2 => Nat.eqb n1 n2 && Nat.eqb l1 l2 && Nat.eqb k1 k2 && configEqb r1 r2",
         "  | _, _ => false",
         "  end.", "",
         "Definition observed : list (nat * list (nat * nat * nat)) := ["]
    L += [f"  ({z}, [{triples(occ, '({n}, {l}, {k})').replace(', (', '; (')}])" + (";" if i < len(atoms) - 1 else "")
          for i, (z, _, occ) in enumerate(atoms)]
    L += ["].", "",
          f"Lemma madelung_electrons_check : forallb (fun z => Nat.eqb (electrons (madelung z)) z) (seq 0 {ZMAX + 1}) = true.",
          "Proof. vm_compute. reflexivity. Qed.",
          f"Lemma madelung_electrons (z : nat) : z <= {ZMAX} -> electrons (madelung z) = z.",
          "Proof.",
          "  intro Hz. apply Nat.eqb_eq.",
          "  apply (proj1 (forallb_forall _ _) madelung_electrons_check).",
          "  apply in_seq. lia.",
          "Qed.",
          f"Lemma madelung_withinCapacity_check : forallb (fun z => withinCapacity (madelung z)) (seq 0 {ZMAX + 1}) = true.",
          "Proof. vm_compute. reflexivity. Qed.",
          "Lemma observed_atomic_numbers : map fst observed = seq 1 " + str(len(atoms)) + ".",
          "Proof. vm_compute. reflexivity. Qed.",
          "Lemma observed_electrons : forallb (fun e => Nat.eqb (electrons (snd e)) (fst e)) observed = true.",
          "Proof. vm_compute. reflexivity. Qed.",
          "Lemma observed_withinCapacity : forallb (fun e => withinCapacity (snd e)) observed = true.",
          "Proof. vm_compute. reflexivity. Qed.",
          "Lemma madelung_exceptions :",
          "  map fst (filter (fun e => negb (configEqb (snd e) (madelung (fst e)))) observed) =",
          "    [" + "; ".join(map(str, exceptions)) + "].",
          "Proof. vm_compute. reflexivity. Qed.", ""]
    return "\n".join(L)


# --------------------------------------------------------------------------------------------------- Agda

def agda(doc, atoms, exceptions) -> str:
    src = doc["source"]
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", f"-- {HEADER}",
         f"-- Ground states Z = 1 … 103 cited from the NIST Atomic Spectra Database ({src['retrieved']}); the Madelung",
         "-- prediction computed; every check holds by `refl`. Twin of Lean/Chem/GroundStates.lean.", "",
         "{-# OPTIONS --without-K --safe #-}", "", "module Chem.GroundStates where", "",
         "open import Data.Bool using (Bool; true; false; _∧_; not)",
         "open import Data.List using (List; []; _∷_; map; filterᵇ; upTo; foldr)",
         "open import Data.Nat using (ℕ; zero; suc; _+_; _*_; _∸_; _⊓_; _≡ᵇ_; _<ᵇ_; _≤ᵇ_)",
         "open import Data.Product using (_×_; _,_; proj₁; proj₂)",
         "open import Relation.Binary.PropositionalEquality using (_≡_; refl)", "",
         "allᵇ : {A : Set} → (A → Bool) → List A → Bool",
         "allᵇ p = foldr (λ x acc → p x ∧ acc) true", "",
         "Subshell : Set", "Subshell = ℕ × ℕ", "", "Occupancy : Set", "Occupancy = ℕ × ℕ × ℕ", "",
         "capacity : Subshell → ℕ", "capacity (_ , l) = 2 * (2 * l + 1)", "",
         "madelungRank : Subshell → ℕ", "madelungRank (n , l) = (n + l) * 8 + n", "",
         "madelungOrder : List Subshell",
         "madelungOrder = " + " ∷ ".join(f"({n} , {l})" for n, l in ORDER) + " ∷ []", "",
         "sortedᵇ : List Subshell → Bool",
         "sortedᵇ (a ∷ b ∷ rest) = (madelungRank a <ᵇ madelungRank b) ∧ sortedᵇ (b ∷ rest)",
         "sortedᵇ _ = true", "",
         "madelungOrder-sorted : sortedᵇ madelungOrder ≡ true", "madelungOrder-sorted = refl", "",
         "fill : List Subshell → ℕ → List Occupancy",
         "fill [] _ = []", "fill (_ ∷ _) zero = []",
         "fill ((n , l) ∷ rest) (suc z) = (n , l , k) ∷ fill rest (suc z ∸ k)",
         "  where k = capacity (n , l) ⊓ suc z", "",
         "madelung : ℕ → List Occupancy", "madelung = fill madelungOrder", "",
         "electrons : List Occupancy → ℕ", "electrons = foldr (λ x acc → proj₂ (proj₂ x) + acc) 0", "",
         "withinCapacity : List Occupancy → Bool",
         "withinCapacity = allᵇ (λ where (n , l , k) → k ≤ᵇ capacity (n , l))", "",
         "configᵇ : List Occupancy → List Occupancy → Bool",
         "configᵇ [] [] = true",
         "configᵇ ((n₁ , l₁ , k₁) ∷ r₁) ((n₂ , l₂ , k₂) ∷ r₂) = (n₁ ≡ᵇ n₂) ∧ (l₁ ≡ᵇ l₂) ∧ (k₁ ≡ᵇ k₂) ∧ configᵇ r₁ r₂",
         "configᵇ _ _ = false", "",
         "observed : List (ℕ × List Occupancy)", "observed ="]
    L += [f"  ({z} , {(' ∷ '.join(f'({n} , {l} , {k})' for n, l, k in occ)) + ' ∷ []'}) ∷" for z, _, occ in atoms]
    L += ["  []", "",
          f"madelung-electrons : allᵇ (λ z → electrons (madelung z) ≡ᵇ z) (upTo {ZMAX + 1}) ≡ true",
          "madelung-electrons = refl", "",
          f"madelung-withinCapacity : allᵇ (λ z → withinCapacity (madelung z)) (upTo {ZMAX + 1}) ≡ true",
          "madelung-withinCapacity = refl", "",
          "observed-electrons : allᵇ (λ e → electrons (proj₂ e) ≡ᵇ proj₁ e) observed ≡ true",
          "observed-electrons = refl", "",
          "observed-withinCapacity : allᵇ (λ e → withinCapacity (proj₂ e)) observed ≡ true",
          "observed-withinCapacity = refl", "",
          "madelung-exceptions :",
          "  map proj₁ (filterᵇ (λ e → not (configᵇ (proj₂ e) (madelung (proj₁ e)))) observed) ≡",
          "    " + " ∷ ".join(map(str, exceptions)) + " ∷ []",
          "madelung-exceptions = refl", ""]
    return "\n".join(L)


# --------------------------------------------------------------------------------------------------- Haskell

def haskell(doc, atoms, exceptions) -> str:
    src = doc["source"]
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", f"-- {HEADER}", "-- |",
         f"-- Ground states Z = 1 … 103 cited from the NIST Atomic Spectra Database ({src['retrieved']}); the Madelung",
         "-- prediction computed. Twin of Lean/Chem/GroundStates.lean; 'checks' lists the statements every language",
         "-- proves, and the test suite runs them.",
         "module UMST.Chem.GroundStates where", "",
         "type Occupancy = (Int, Int, Int)", "",
         "capacity :: (Int, Int) -> Int", "capacity (_, l) = 2 * (2 * l + 1)", "",
         "madelungRank :: (Int, Int) -> Int", "madelungRank (n, l) = (n + l) * 8 + n", "",
         "madelungOrder :: [(Int, Int)]",
         "madelungOrder = [" + ", ".join(f"({n}, {l})" for n, l in ORDER) + "]", "",
         "fill :: [(Int, Int)] -> Int -> [Occupancy]",
         "fill [] _ = []",
         "fill ((n, l) : rest) z",
         "  | z <= 0 = []",
         "  | otherwise = let k = min (capacity (n, l)) z in (n, l, k) : fill rest (z - k)", "",
         "madelung :: Int -> [Occupancy]", "madelung = fill madelungOrder", "",
         "electrons :: [Occupancy] -> Int", "electrons c = sum [k | (_, _, k) <- c]", "",
         "withinCapacity :: [Occupancy] -> Bool", "withinCapacity = all (\\(n, l, k) -> k <= capacity (n, l))", "",
         "-- | Cited ground states (NIST ASD), expanded to full occupancies.",
         "observed :: [(Int, [Occupancy])]", "observed ="]
    L += [("  [ " if i == 0 else "  , ") + f"({z}, [{triples(occ, '({n}, {l}, {k})')}])" for i, (z, _, occ) in enumerate(atoms)]
    L += ["  ]", "",
          "-- | Each statement the proof languages prove, as a checked value.",
          "checks :: [(String, Bool)]", "checks =",
          "  [ (\"madelung order sorted\", and (zipWith (\\a b -> madelungRank a < madelungRank b) madelungOrder (drop 1 madelungOrder)))",
          f"  , (\"madelung electrons\", all (\\z -> electrons (madelung z) == z) [0 .. {ZMAX}])",
          f"  , (\"madelung within capacity\", all (withinCapacity . madelung) [0 .. {ZMAX}])",
          "  , (\"observed electrons\", all (\\(z, c) -> electrons c == z) observed)",
          "  , (\"observed within capacity\", all (withinCapacity . snd) observed)",
          "  , (\"observed atomic numbers\", map fst observed == [1 .. " + str(len(atoms)) + "])",
          "  , (\"madelung exceptions\", [z | (z, c) <- observed, c /= madelung z] == [" + ", ".join(map(str, exceptions)) + "])",
          "  ]", ""]
    return "\n".join(L)


def outputs() -> dict[str, str]:
    doc, atoms, exceptions = load()
    return {"Lean/Chem/GroundStates.lean": lean(doc, atoms, exceptions),
            "Coq/Chem/GroundStates.v": coq(doc, atoms, exceptions),
            "Agda/Chem/GroundStates.agda": agda(doc, atoms, exceptions),
            "Haskell/src/UMST/Chem/GroundStates.hs": haskell(doc, atoms, exceptions)}


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for rel, text in outputs().items():
        path = os.path.join(ROOT, rel)
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old != text:
            stale.append(rel)
            if not check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                open(path, "w", encoding="utf-8").write(text)
    if check and stale:
        print("FAIL: ground-state modules are stale: " + ", ".join(stale) + " (run scripts/gen_ground_states.py)",
              file=sys.stderr)
        return 1
    print("OK: ground-state modules are current" if check else "wrote: " + ", ".join(stale or ["nothing changed"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
