#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
# SPDX-License-Identifier: MIT
"""Generate the constants modules and README tables from constants/constants.json (one source, four languages).

Byte-identical in umst-formal and umst-formal-double-slit, and so is constants/constants.json
(scripts/check_shared_lean_drift.sh compares both with the sibling). Every value is an exact rational, so each
language checks it by exact computation:

  cited     a defining constant of the SI (or another cited authority): a definition with its authority
  measured  a cited measurement: the value and its standard uncertainty, both exact rationals
  derived   a definition by its formula, and two theorems: `<id>_value` (the formula equals the exact value) and
            `<id>_derivation` (the value times the formula's denominator equals its numerator, the statement every
            language proves the same way; Agda proves it on unnormalised rationals by `refl`). A formula is a
            monomial (a product and quotient of constants and integers) or linear (a sum and difference of
            constants and integers); a linear formula's `_value` is its derivation, and Agda states it as
            `<id> ≃ <formula>` by `refl`
  crosscheck  for a derived row with a published value: |derived − published| ≤ published uncertainty, or, with
            "bound": "propagated", ≤ the uncertainty its measured inputs carry to first order (Σ |exponent| · u/x of
            each measured factor, times the derived value): for a published value itself adjusted from other data
            (CODATA's m_e from R∞), whose own uncertainty is smaller than its inputs' rounding
  policy    a documented model or configuration choice, never counted as a constant: its value, its reason, and the
            range it must lie in, given by two rows of the table; `<id>_in_range` proves low ≤ value ≤ high

A second table, `bounds`, holds the second-law bounds: each entry ("kind": "bound") confines a quantity to an
interval with exact rational endpoints (`lower`, `upper`, each {num, den, strict} or null) and names the theorem that
proves it ("theorem", a Lean name listed in formal_parity.json) and the languages that state it ("languages", which
must equal the languages formal_parity.json lists for that theorem). A bound fixes no value: the value stays cited,
measured or chosen, and the bound states the interval the second law admits. "unit" is null only when every finite
endpoint is zero (a sign, the same in every unit). An entry with "row" confines that row of the constants table, and
each language proves the row's exact value lies inside (`<id>_admits`). In umst-formal each language gains a bounds
module (Lean `Constants.Bounds`, Coq `Constants/Bounds.v`, Agda `Constants.Bounds`, Haskell `UMST.Constants.Bounds`
and the test module `ConstantsBoundsProps`) that names the theorem itself, so renaming or removing it breaks the
build, and umst-constants gains `Bound` with a `const fn admits`. umst-formal-double-slit carries neither the
theorems nor the bounds modules and generates nothing from this table.

Lean (umst-formal only; umst-formal-double-slit imports it through Lake), Coq, Agda and Haskell modules are written,
and in umst-formal the no_std Rust crate constants-rs (umst-constants), each where the repository keeps that
language. `--check` regenerates in memory and fails on any difference.
"""
from __future__ import annotations

import json
import math
import os
import re
import sys
import textwrap
from fractions import Fraction

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))


def repo_name(root: str) -> str:
    """The repository by its Lake package name, so a worktree or a copy under another directory name generates the
    same files; the directory name when no lakefile names a package."""
    try:
        with open(os.path.join(root, "Lean/lakefile.lean"), encoding="utf-8") as f:
            m = re.search(r"(?m)^package\s+«?([\w-]+)»?", f.read())
    except OSError:
        m = None
    return m.group(1) if m else os.path.basename(root)


REPO = repo_name(ROOT)
HOME = "umst-formal"  # the Lean module lives here; the sibling imports it
FIBRE = {"umst-formal": "acting", "umst-formal-double-slit": "knowing"}.get(REPO, "acting")
SPDX = "SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar"
HEADER = "Generated by scripts/gen_constants.py from constants/constants.json; edit the table, not this file."


def big(text: str) -> int:
    """`602214076*10^15`, `10^42` or a plain integer."""
    value = 1
    for factor in text.split("*"):
        base, _, exp = factor.strip().partition("^")
        value *= int(base) ** (int(exp) if exp else 1)
    return value


def tokens(formula: str) -> list[str]:
    return re.findall(r"[A-Za-z_]\w*|\d+|[()*/]", formula)


def factors(formula: str) -> list[tuple[str, int]]:
    """A product of factors with exponents ±1 (the formulas are monomials)."""
    toks = tokens(formula)
    pos = 0

    def expr(sign: int) -> list[tuple[str, int]]:
        nonlocal pos
        out = term(sign)
        while pos < len(toks) and toks[pos] in "*/":
            op = toks[pos]
            pos += 1
            out += term(sign if op == "*" else -sign)
        return out

    def term(sign: int) -> list[tuple[str, int]]:
        nonlocal pos
        tok = toks[pos]
        pos += 1
        if tok == "(":
            inner = expr(sign)
            pos += 1  # ')'
            return inner
        return [(tok, sign)]

    return expr(1)


def linear(formula: str) -> bool:
    """A sum or difference of constants and integers (no product or quotient)."""
    return bool(re.search(r"[+-]", formula))


def terms(formula: str) -> list[tuple[str, int]]:
    """The signed terms of a linear formula."""
    out, sign = [], 1
    for tok in re.findall(r"[A-Za-z_]\w*|\d+|[+-]", formula):
        if tok in "+-":
            sign = 1 if tok == "+" else -1
        else:
            out.append((tok, sign))
            sign = 1
    return out


def load() -> dict:
    with open(os.path.join(ROOT, "constants/constants.json"), encoding="utf-8") as f:
        return json.load(f)


def values(table: dict) -> dict[str, Fraction]:
    out: dict[str, Fraction] = {}
    for c in table["constants"]:
        if c["status"] in ("cited", "measured", "policy"):
            out[c["id"]] = Fraction(big(c["num"]), big(c["den"]))
    for c in table["constants"]:
        if c["status"] == "derived":
            value = lambda name: Fraction(int(name)) if name.isdigit() else out[name]
            if linear(c["formula"]):
                v = sum((sign * value(name) for name, sign in terms(c["formula"])), Fraction(0))
            else:
                v = Fraction(1)
                for name, sign in factors(c["formula"]):
                    v = v * value(name) if sign > 0 else v / value(name)
            out[c["id"]] = v
    return out


def split(c: dict) -> tuple[list[str], list[str]]:
    if linear(c["formula"]):
        return [], []  # a linear formula has no denominator; its `_value` is its derivation
    fs = factors(c["formula"])
    return [n for n, s in fs if s > 0], [n for n, s in fs if s < 0]


def frac(c: dict, prefix: str) -> Fraction:
    return Fraction(big(c[prefix + "num"]), big(c[prefix + "den"]))


def crossbound(c: dict, table: dict, vals: dict[str, Fraction]) -> tuple[Fraction, Fraction]:
    """The published value of a derived row's cross-check and the bound its distance must meet."""
    x = c["crosscheck"]
    if x.get("bound") != "propagated":
        return frac(x, ""), frac(x, "uncertainty_")
    rows = {r["id"]: r for r in table["constants"]}
    rel = sum((frac(rows[n], "uncertainty_") / vals[n] for n, _ in factors(c["formula"])
               if n in rows and rows[n]["status"] == "measured"), Fraction(0))
    return frac(x, ""), abs(vals[c["id"]]) * rel


def crosswhat(c: dict) -> str:
    x = c["crosscheck"]
    return (f"the uncertainty its measured inputs carry (first order), from the {x['authority']} value"
            if x.get("bound") == "propagated" else f"the {x['authority']} value's standard uncertainty")


# ------------------------------------------------------------------------------------------------- Lean (ℚ)

def lean_q(v: Fraction) -> str:
    return f"({v.numerator} : ℚ)" if v.denominator == 1 else f"({v.numerator} : ℚ) / {v.denominator}"


def lean(table: dict, vals: dict[str, Fraction]) -> str:
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", "/-", f"  {HEADER}", "",
         "  The constants of the UMST ecosystem as exact rationals: the seven defining constants of the SI (cited),",
         "  cited measurements with their standard uncertainty, and constants derived from them, each with its exact",
         "  value and its defining equation proved by computation. `Constants.SIBridge` identifies these values with",
         "  the real-valued constants of the Landauer chain and states the laws that carry the second law.", "-/", "",
         "import Mathlib.Tactic.NormNum", "import Mathlib.Algebra.Order.Group.Abs", "", "namespace UMST.Constants.SI", ""]
    ids = [c["id"] for c in table["constants"]]
    for c in table["constants"]:
        doc = f"/-- {c['symbol']}: {c['name']} [{c['unit']}]"
        if c["status"] == "cited":
            L += [doc + f"; cited: {table['authorities'][c['authority']].split(':')[0]}. -/",
                  f"def {c['id']} : ℚ := {lean_q(frac(c, ''))}", ""]
        elif c["status"] == "measured":
            L += [doc + f"; measured, cited from {c['authority']}. -/", f"def {c['id']} : ℚ := {lean_q(frac(c, ''))}",
                  f"/-- Standard uncertainty of {c['symbol']} ({c['authority']}). -/",
                  f"def {c['id']}Uncertainty : ℚ := {lean_q(frac(c, 'uncertainty_'))}", ""]
        elif c["status"] == "policy":
            lo, hi = c["range"]["low"], c["range"]["high"]
            L += [doc + f"; policy (a model choice, not a constant): {c['reason']}. -/",
                  f"def {c['id']} : ℚ := {lean_q(frac(c, ''))}", "",
                  f"/-- The choice lies in its range [{lo}, {hi}]. -/",
                  f"theorem {c['id']}_in_range : {lo} ≤ {c['id']} ∧ {c['id']} ≤ {hi} := by",
                  f"  norm_num [{c['id']}, {lo}, {hi}]", ""]
        else:
            num, den = split(c)
            deps, todo = [], [c["id"]]  # every constant the formula reaches, so norm_num evaluates it
            formulas = {r["id"]: r.get("formula", "") for r in table["constants"]}
            while todo:
                for x in re.findall(r"[A-Za-z_]\w*", formulas.get(todo.pop(), "")):
                    if x in formulas and x not in deps:
                        deps.append(x)
                        todo.append(x)
            unfold = ", ".join(x for x in ids if x in deps) or c["id"]
            prod = lambda xs: " * ".join(xs) if xs else "1"
            L += [doc + f"; derived: {c['formula']}. -/", f"def {c['id']} : ℚ := {c['formula']}", "",
                  f"theorem {c['id']}_value : {c['id']} = {lean_q(vals[c['id']])} := by",
                  f"  norm_num [{c['id']}, {unfold}]", "",
                  ]
            if den:  # with a denominator the multiplicative form is a second statement; without one, `_value` is it
                L += [f"theorem {c['id']}_derivation : {lean_q(vals[c['id']])} * ({prod(den)}) = {prod(num)} := by",
                      f"  norm_num [{unfold}]", ""]
            if "crosscheck" in c:
                x = c["crosscheck"]
                pub, u = crossbound(c, table, vals)
                L += [f"/-- {c['symbol']} derived here lies within {crosswhat(c)}. -/",
                      f"theorem {c['id']}_within_{x['authority']} :",
                      f"    |{c['id']} - {lean_q(pub)}| ≤ {lean_q(u)} := by",
                      f"  rw [{c['id']}_value, abs_le]", "  constructor <;> norm_num", ""]
    L += ["end UMST.Constants.SI", ""]
    return "\n".join(L)


# ------------------------------------------------------------------------------------------------- Coq (Q)

def coq_q(v: Fraction) -> str:
    num = f"({v.numerator})" if v.numerator < 0 else str(v.numerator)  # `Qmake -1 1` parses as a subtraction
    return f"(Qmake {num} {v.denominator})"


def coq(table: dict, vals: dict[str, Fraction]) -> str:
    L = [f"(* {SPDX} *)", "(* SPDX-License-Identifier: MIT *)", f"(* {HEADER} *)",
         "(* Exact rational constants; each derived constant's value and defining equation are proved by        *)",
         "(* computation (twin of Lean/Constants/SI.lean). Zero Axiom, Parameter or Admitted.                  *)", "",
         "From Stdlib Require Import QArith.", "Open Scope Q_scope.", ""]
    for c in table["constants"]:
        if c["status"] in ("cited", "measured"):
            L.append(f"(* {c['symbol']}: {c['name']} [{c['unit']}], {c['status']} ({c['authority']}) *)")
            L.append(f"Definition {c['id']} : Q := {coq_q(frac(c, ''))}.")
            if c["status"] == "measured":
                L.append(f"Definition {c['id']}Uncertainty : Q := {coq_q(frac(c, 'uncertainty_'))}.")
            L.append("")
        elif c["status"] == "policy":
            lo, hi = c["range"]["low"], c["range"]["high"]
            L += [f"(* {c['symbol']}: {c['name']} [{c['unit']}], policy (a model choice, not a constant): {c['reason']} *)",
                  f"Definition {c['id']} : Q := {coq_q(frac(c, ''))}.",
                  f"Lemma {c['id']}_in_range : {lo} <= {c['id']} /\\ {c['id']} <= {hi}.",
                  "Proof. split; vm_compute; discriminate. Qed.", ""]
        else:
            num, den = split(c)
            prod = lambda xs: " * ".join(xs) if xs else "1"
            L += [f"(* {c['symbol']}: {c['name']} [{c['unit']}], derived: {c['formula']} *)",
                  f"Definition {c['id']} : Q := {c['formula']}.",
                  f"Lemma {c['id']}_value : {c['id']} == {coq_q(vals[c['id']])}.",
                  "Proof. vm_compute. reflexivity. Qed.",
                  ]
            if den:
                L += [f"Lemma {c['id']}_derivation : {coq_q(vals[c['id']])} * ({prod(den)}) == {prod(num)}.",
                      "Proof. vm_compute. reflexivity. Qed."]
            if "crosscheck" in c:
                x = c["crosscheck"]
                pub, u = crossbound(c, table, vals)
                L += [f"Lemma {c['id']}_within_{x['authority']} :",
                      f"  {coq_q(pub - u)} <= {c['id']} /\\ {c['id']} <= {coq_q(pub + u)}.",
                      "Proof. split; vm_compute; discriminate. Qed."]
            L.append("")
    return "\n".join(L)


# ------------------------------------------------------------------------------------------------- Agda (ℚᵘ)

def agda_q(v: Fraction) -> str:
    sign = "-[1+ " + str(-v.numerator - 1) + " ]" if v.numerator < 0 else f"+ {v.numerator}"
    return f"(mkℚᵘ ({sign}) {v.denominator - 1})"


def agda(table: dict, vals: dict[str, Fraction]) -> str:
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", f"-- {HEADER}",
         "-- Exact constants on unnormalised rationals: each derived constant's defining equation holds by `refl`",
         "-- (cross-multiplication of integers, no normalisation). Twin of Lean/Constants/SI.lean.", "",
         "{-# OPTIONS --without-K --safe #-}", "", "module Constants.SI where", "",
         "open import Data.Integer using (+_; -[1+_])",
         "open import Data.Rational.Unnormalised.Base using (ℚᵘ; mkℚᵘ; _*_; _+_; _-_; _≃_; *≡*; _≤_; *≤*)",
         "open import Data.Product using (_×_; _,_)",
         "open import Relation.Binary.PropositionalEquality using (refl)",
         "open import Relation.Nullary.Decidable using (toWitness)",
         "import Data.Integer.Properties as ℤ", "",
         "private", "  two : ℚᵘ", "  two = mkℚᵘ (+ 2) 0", ""]
    for c in table["constants"]:
        if c["status"] in ("cited", "measured"):
            L += [f"-- {c['symbol']}: {c['name']} [{c['unit']}], {c['status']} ({c['authority']})",
                  f"{c['id']} : ℚᵘ", f"{c['id']} = {agda_q(frac(c, ''))}"]
            if c["status"] == "measured":
                L += [f"{c['id']}Uncertainty : ℚᵘ", f"{c['id']}Uncertainty = {agda_q(frac(c, 'uncertainty_'))}"]
            L.append("")
        elif c["status"] == "policy":
            lo, hi = c["range"]["low"], c["range"]["high"]
            L += [f"-- {c['symbol']}: {c['name']} [{c['unit']}], policy (a model choice, not a constant): {c['reason']}",
                  f"{c['id']} : ℚᵘ", f"{c['id']} = {agda_q(frac(c, ''))}", "",
                  f"{c['id']}-in-range : ({lo} ≤ {c['id']}) × ({c['id']} ≤ {hi})",
                  f"{c['id']}-in-range = *≤* (toWitness {{a? = _ ℤ.≤? _}} _) , *≤* (toWitness {{a? = _ ℤ.≤? _}} _)", ""]
        else:
            num, den = split(c)
            term = lambda xs: " * ".join("two" if x == "2" else x for x in xs) if xs else "mkℚᵘ (+ 1) 0"
            if linear(c["formula"]):
                lit = lambda n: agda_q(Fraction(int(n))) if n.isdigit() else n
                rhs = re.sub(r"[A-Za-z_]\w*|\d+", lambda m: lit(m.group(0)), c["formula"])
                statement = f"{c['id']} ≃ {rhs}"
            else:
                statement = f"{c['id'] + (' * (' + term(den) + ')' if den else '')} ≃ {term(num)}"
            L += [f"-- {c['symbol']}: {c['name']} [{c['unit']}], derived: {c['formula']}",
                  f"{c['id']} : ℚᵘ", f"{c['id']} = {agda_q(vals[c['id']])}", "",
                  f"{c['id']}-derivation : {statement}",
                  f"{c['id']}-derivation = *≡* refl", ""]
            if "crosscheck" in c:
                x = c["crosscheck"]
                pub, u = crossbound(c, table, vals)
                L += [f"{c['id']}-within-{x['authority']} : ({agda_q(pub - u)} ≤ {c['id']}) × ({c['id']} ≤ {agda_q(pub + u)})",
                      f"{c['id']}-within-{x['authority']} = *≤* (toWitness {{a? = _ ℤ.≤? _}} _) , *≤* (toWitness {{a? = _ ℤ.≤? _}} _)", ""]
    return "\n".join(L)


# ------------------------------------------------------------------------------------------------- Haskell (Rational)

def haskell(table: dict, vals: dict[str, Fraction]) -> str:
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", f"-- {HEADER}", "-- |",
         "-- Exact constants as 'Rational' (twin of Lean/Constants/SI.lean): the runtime reads these values and",
         "-- 'derivations' lists every derived constant's defining equation, checked by the test suite.",
         "module UMST.Constants.SI where", "", "import Data.Ratio ((%))", ""]
    for c in table["constants"]:
        if c["status"] in ("cited", "measured"):
            v = frac(c, "")
            L += [f"-- | {c['symbol']}: {c['name']} [{c['unit']}], {c['status']} ({c['authority']}).",
                  f"{c['id']} :: Rational", f"{c['id']} = {v.numerator} % {v.denominator}"]
            if c["status"] == "measured":
                u = frac(c, "uncertainty_")
                L += [f"{c['id']}Uncertainty :: Rational", f"{c['id']}Uncertainty = {u.numerator} % {u.denominator}"]
            L.append("")
        elif c["status"] == "policy":
            v = frac(c, "")
            L += [f"-- | {c['symbol']}: {c['name']} [{c['unit']}], policy (a model choice, not a constant): {c['reason']}.",
                  f"{c['id']} :: Rational", f"{c['id']} = {v.numerator} % {v.denominator}", ""]
        else:
            v = vals[c["id"]]
            L += [f"-- | {c['symbol']}: {c['name']} [{c['unit']}], derived: {c['formula']}.",
                  f"{c['id']} :: Rational", f"{c['id']} = {c['formula']}", ""]
    L += ["-- | Each derived constant against its exact value, and each cross-check against its published value.",
          "derivations :: [(String, Bool)]", "derivations ="]
    rows = []
    for c in table["constants"]:
        if c["status"] == "derived":
            v = vals[c["id"]]
            rows.append(f'("{c["id"]}", {c["id"]} == {v.numerator} % {v.denominator})')
            if "crosscheck" in c:
                x = c["crosscheck"]
                pub, u = crossbound(c, table, vals)
                rows.append(f'("{c["id"]} within {x["authority"]}", abs ({c["id"]} - {pub.numerator} % {pub.denominator}) <= {u.numerator} % {u.denominator})')
        if c["status"] == "policy":
            rows.append(f'("{c["id"]} in its range", {c["range"]["low"]} <= {c["id"]} && {c["id"]} <= {c["range"]["high"]})')
    L += ["  [ " + "\n  , ".join(rows), "  ]", ""]
    return "\n".join(L)


# ------------------------------------------------------------------------------------------------- Rust (no_std)

def rust_name(ident: str) -> str:
    return re.sub(r"(?<=[a-z])(?=[A-Z])", "_", ident).upper()


def rust_f64(v: Fraction) -> str:
    """The shortest literal that round-trips to the nearest double (Fraction to float is correctly rounded), with
    the exponent written as Rust writes it (`e16`, `e-6`)."""
    text = repr(float(v))
    if "e" in text:
        mant, exp = text.split("e")
        text = f"{mant}e{int(exp)}"
    return text if any(ch in text for ch in ".e") else text + ".0"


def rust(table: dict, vals: dict[str, Fraction]) -> str:
    kinds = {"cited": "Cited", "measured": "Measured", "derived": "Derived", "policy": "Policy"}
    L = [f"// {SPDX}", "// SPDX-License-Identifier: MIT", f"// {HEADER}",
         "//! The constants of the UMST ecosystem for the Rust runtime: each row's value as the nearest `f64`, its exact",
         "//! rational, provenance and unit, from constants/constants.json, the table Lean, Coq, Agda and Haskell prove.",
         "//! Constants are `const` items: reading one costs nothing at run time.", "",
         "#![no_std]", "#![forbid(unsafe_code)]", "",
         "/// Provenance of a row: cited (a defining constant or cited value), measured (with standard uncertainty),",
         "/// derived (a theorem in Lean, Coq and Agda from other rows) or policy (a model choice in a proved range).",
         "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
         "pub enum Kind {", "    Cited,", "    Measured,", "    Derived,", "    Policy,", "}", "",
         "/// One row of the table.", "#[derive(Clone, Copy, Debug, PartialEq)]", "pub struct Row {",
         "    pub id: &'static str,", "    pub symbol: &'static str,", "    pub unit: &'static str,", "    pub kind: Kind,",
         "    /// The nearest `f64` to the exact value.", "    pub value: f64,",
         "    /// The exact value as a rational of decimal integers.", "    pub exact_num: &'static str,",
         "    pub exact_den: &'static str,", "    /// Standard uncertainty of a measured row.",
         "    pub uncertainty: Option<f64>,", "}", ""]
    for c in table["constants"]:
        v = vals[c["id"]]
        how = (c.get("formula") and f"derived: {c['formula']}") or (c["status"] == "policy" and f"policy: {c['reason']}") \
            or f"{c['status']} ({c.get('authority', '')})"
        L += [f"/// {c['symbol']}: {c['name']} [{c['unit']}]; {how}.", f"pub const {rust_name(c['id'])}: f64 = {rust_f64(v)};", ""]
    for c in table["constants"]:
        if c["status"] == "policy":
            lo, hi = rust_name(c["range"]["low"]), rust_name(c["range"]["high"])
            me = rust_name(c["id"])
            one = f"const _: () = assert!({lo} <= {me} && {me} <= {hi});"
            body = [one] if len(one) <= 100 else ["const _: () = assert!(", f"    {lo} <= {me}", f"        && {me} <= {hi}", ");"]
            L += [f"/// The policy {me} lies in its range [{lo}, {hi}], checked at compile time."] + body + [""]
    L += ["/// Every row, in table order.", "pub const ROWS: &[Row] = &["]
    for c in table["constants"]:
        v = vals[c["id"]]
        unc = f"Some({rust_f64(frac(c, 'uncertainty_'))})" if c["status"] == "measured" else "None"
        L += ["    Row {", f'        id: "{c["id"]}",', f'        symbol: "{c["symbol"]}",', f'        unit: "{c["unit"]}",',
              f"        kind: Kind::{kinds[c['status']]},", f"        value: {rust_name(c['id'])},",
              f'        exact_num: "{v.numerator}",', f'        exact_den: "{v.denominator}",', f"        uncertainty: {unc},", "    },"]
    L += ["];", ""]
    L += rust_bounds(table, vals)
    L += ["#[cfg(test)]", "#[rustfmt::skip] // generated: one assertion per row", "mod tests {", "    use super::*;", "",
          "    fn close(a: f64, b: f64) -> bool {", "        (a - b).abs() <= 8.0 * f64::EPSILON * a.abs().max(b.abs())", "    }", "",
          "    /// Each derived row equals its formula evaluated on the rows it reads.", "    #[test]",
          "    fn derived_rows_follow_their_formulas() {"]
    for c in table["constants"]:
        if c["status"] == "derived":
            expr = re.sub(r"[A-Za-z_]\w*|\d+", lambda m: rust_name(m.group(0)) if not m.group(0).isdigit() else m.group(0) + ".0",
                          c["formula"])
            L.append(f"        assert!(close({rust_name(c['id'])}, {expr}), \"{c['id']}\");")
    L += ["    }", "", "    #[test]", "    fn rows_name_each_constant_once() {",
          "        for (i, a) in ROWS.iter().enumerate() {", "            for b in &ROWS[i + 1..] {",
          "                assert_ne!(a.id, b.id);", "            }", "        }", "    }"]
    if bound_rows(table):
        L += ["", "    /// `admits` refuses NaN and the infinity past each endpoint, and takes an endpoint exactly when it is",
              "    /// not strict.", "    #[test]", "    fn bounds_admit_by_their_endpoints() {", "        for b in BOUNDS {",
              "            assert!(!b.admits(f64::NAN), \"{}\", b.id);", "            if let Some(e) = b.lower {",
              "                assert!(!b.admits(f64::NEG_INFINITY), \"{}\", b.id);",
              "                if b.upper.is_none() {",
              "                    assert_eq!(b.admits(e.at), !e.strict, \"{}\", b.id);", "                }",
              "            }", "            if let Some(e) = b.upper {",
              "                assert!(!b.admits(f64::INFINITY), \"{}\", b.id);",
              "                if b.lower.is_none() {",
              "                    assert_eq!(b.admits(e.at), !e.strict, \"{}\", b.id);", "                }",
              "            }", "        }", "    }"]
    L += ["}", ""]
    return "\n".join(L)


# ------------------------------------------------------------------------------------------------- second-law bounds

LANGS = ("lean", "coq", "agda", "haskell")


def bound_rows(table: dict) -> list[dict]:
    """The second-law bounds, each in umst-formal only (umst-formal-double-slit holds none of their theorems)."""
    return table.get("bounds", []) if REPO == HOME else []


def endpoint(e: dict | None) -> tuple[Fraction, bool] | None:
    return None if e is None else (Fraction(big(e["num"]), big(e["den"])), bool(e["strict"]))


def admitted(b: dict, v: Fraction) -> bool:
    """Whether the exact value `v` lies in the bound's interval."""
    lo, hi = endpoint(b.get("lower")), endpoint(b.get("upper"))
    return (lo is None or (lo[0] < v if lo[1] else lo[0] <= v)) and (hi is None or (v < hi[0] if hi[1] else v <= hi[0]))


def parity_statements(root: str = ROOT) -> dict[str, dict]:
    """formal_parity.json statements by Lean declaration name."""
    path = os.path.join(root, "formal_parity.json")
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as f:
        doc = json.load(f)
    return {st["lean"]["name"]: st for st in doc.get("statements", []) if "name" in (st.get("lean") or {})}


def stated_in(st: dict) -> list[str]:
    return [lang for lang in LANGS if "absent" not in (st.get(lang) or {"absent": True})]


def bound_problems(table: dict, vals: dict[str, Fraction], parity: dict[str, dict]) -> list[str]:
    """Every reason the bounds table cannot be generated; empty when each entry is well formed and proved."""
    out, seen = [], {c["id"] for c in table["constants"]}
    units = {c["id"]: c["unit"] for c in table["constants"]}
    for b in table.get("bounds", []):
        i = b.get("id", "?")
        if b.get("kind") != "bound":
            out.append(f"{i}: kind must be \"bound\"")
        if i in seen:
            out.append(f"{i}: the id is already a row or a bound")
        seen.add(i)
        lo, hi = endpoint(b.get("lower")), endpoint(b.get("upper"))
        if lo is None and hi is None:
            out.append(f"{i}: a bound needs a lower or an upper endpoint")
        if lo and hi and (lo[0] > hi[0] or lo[0] == hi[0] and (lo[1] or hi[1])):
            out.append(f"{i}: the interval is empty")
        if b.get("unit") is None and any(e and e[0] != 0 for e in (lo, hi)):
            out.append(f"{i}: a bound without a unit may only have zero endpoints")
        st = parity.get(b.get("theorem", ""))
        if st is None:
            out.append(f"{i}: theorem {b.get('theorem')} is not a Lean name in formal_parity.json")
        elif sorted(b.get("languages", [])) != sorted(stated_in(st)):
            out.append(f"{i}: languages {b.get('languages')} differ from formal_parity.json {stated_in(st)}")
        r = b.get("row")
        if r is not None:
            if r not in vals:
                out.append(f"{i}: row {r} is not in the constants table")
            elif units[r] != b.get("unit"):
                out.append(f"{i}: row {r} is in {units[r]}, the bound in {b.get('unit')}")
            elif not admitted(b, vals[r]):
                out.append(f"{i}: row {r} = {vals[r]} lies outside the bound")
    return out


def interval(b: dict) -> str:
    lo, hi = endpoint(b.get("lower")), endpoint(b.get("upper"))
    left = "(−∞" if lo is None else ("(" if lo[1] else "[") + str(lo[0])
    right = "∞)" if hi is None else str(hi[0]) + (")" if hi[1] else "]")
    return f"{left}, {right}"


def unit_text(b: dict) -> str:
    return b["unit"] if b.get("unit") is not None else "any unit"


def bound_doc(b: dict, st: dict, first: str, rest: str, end: str = "", width: int = 116) -> list[str]:
    """The bound's description, wrapped: quantity, unit, interval, and the formal_parity.json statement that proves
    it."""
    text = (f"{b['symbol']}: {b['quantity']} [{unit_text(b)}] lies in {interval(b)}; proved by {b['theorem']} "
            f"({st['id']}: {st['statement']}).{end}")
    lines = textwrap.wrap(text, width - len(first), break_on_hyphens=False)
    return [first + lines[0]] + [rest + x for x in lines[1:]]


def module_of(path: str, prefix: str, suffix: str) -> str:
    return path[len(prefix):-len(suffix)].replace("/", ".")


def lean_bounds(table: dict, parity: dict[str, dict]) -> str:
    bs = bound_rows(table)
    mods = sorted({module_of(parity[b["theorem"]]["lean"]["file"], "Lean/", ".lean") for b in bs})
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", "/-", f"  {HEADER}", "",
         "  The second-law bounds of the constants table. Each bound confines a quantity to an interval with exact",
         "  rational endpoints and names, as `<id>_theorem`, the theorem of formal_parity.json that proves it: a",
         "  renamed or removed theorem fails this module. A bound on a row of the table proves the row's exact value",
         "  lies inside (`<id>_admits`). A bound fixes no value; the value stays cited, measured or chosen.", "-/", "",
         "import Constants.SI"] + [f"import {m}" for m in mods] + ["", "namespace UMST.Constants.Bounds", ""]
    for b in bs:
        st = parity[b["theorem"]]
        L += bound_doc(b, st, "/-- ", "    ", " -/")
        for side in ("lower", "upper"):
            e = endpoint(b.get(side))
            if e:
                L += [f"def {b['id']}_{side} : ℚ := {lean_q(e[0])}"]
        L += [f"alias {b['id']}_theorem := {b['theorem']}", ""]
        if b.get("row"):
            row = f"UMST.Constants.SI.{b['row']}"
            conj = []
            lo, hi = endpoint(b.get("lower")), endpoint(b.get("upper"))
            if lo:
                conj.append(f"{b['id']}_lower {'<' if lo[1] else '≤'} {row}")
            if hi:
                conj.append(f"{row} {'<' if hi[1] else '≤'} {b['id']}_upper")
            unfold = (f"rw [{row}_value]; norm_num [{', '.join(b['id'] + '_' + s for s in ('lower', 'upper') if b.get(s))}]"
                      if any(c["id"] == b["row"] and c["status"] == "derived" for c in table["constants"]) else
                      f"norm_num [{row}, {', '.join(b['id'] + '_' + s for s in ('lower', 'upper') if b.get(s))}]")
            L += [f"/-- The table's {b['row']} lies in the bound. -/",
                  f"theorem {b['id']}_admits :", "    " + " ∧\n    ".join(conj) + " := by", f"  {unfold}", ""]
    L += ["end UMST.Constants.Bounds", ""]
    return "\n".join(L)


def coq_bounds(table: dict, parity: dict[str, dict]) -> str:
    bs = bound_rows(table)
    mods = sorted({"UMSTFormal." + module_of(parity[b["theorem"]]["coq"]["file"], "Coq/", ".v") for b in bs})
    L = [f"(* {SPDX} *)", "(* SPDX-License-Identifier: MIT *)", f"(* {HEADER} *)",
         "(* The second-law bounds of the constants table (twin of Lean/Constants/Bounds.lean): exact endpoints,   *)",
         "(* the theorem that proves each bound by name, and for a bound on a table row its value inside.        *)",
         "(* Zero Axiom, Parameter or Admitted.                                                                  *)", "",
         "From Stdlib Require Import QArith.", "Require UMSTFormal.Constants.SI."] + \
        [f"Require {m}." for m in mods] + ["Open Scope Q_scope.", ""]
    for b in bs:
        st = parity[b["theorem"]]
        mod = "UMSTFormal." + module_of(st["coq"]["file"], "Coq/", ".v")
        L += bound_doc(b, st, "(* ", "   ", " *)")
        for side in ("lower", "upper"):
            e = endpoint(b.get(side))
            if e:
                L.append(f"Definition {b['id']}_{side} : Q := {coq_q(e[0])}.")
        L.append(f"Definition {b['id']}_theorem := @{mod}.{st['coq']['name']}.")
        if b.get("row"):
            row = f"UMSTFormal.Constants.SI.{b['row']}"
            lo, hi = endpoint(b.get("lower")), endpoint(b.get("upper"))
            conj, tac = [], []
            if lo:
                conj.append(f"{b['id']}_lower {'<' if lo[1] else '<='} {row}")
                tac.append("reflexivity" if lo[1] else "discriminate")
            if hi:
                conj.append(f"{row} {'<' if hi[1] else '<='} {b['id']}_upper")
                tac.append("reflexivity" if hi[1] else "discriminate")
            proof = f"vm_compute; {tac[0]}" if len(tac) == 1 else f"split; [vm_compute; {tac[0]} | vm_compute; {tac[1]}]"
            L += [f"Lemma {b['id']}_admits : {' /\\ '.join(conj)}.", f"Proof. {proof}. Qed."]
        L.append("")
    return "\n".join(L)


def agda_bounds(table: dict, parity: dict[str, dict]) -> str:
    bs = bound_rows(table)
    mods = sorted({module_of(parity[b["theorem"]]["agda"]["file"], "Agda/", ".agda") for b in bs})
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", f"-- {HEADER}",
         "-- The second-law bounds of the constants table (twin of Lean/Constants/Bounds.lean): exact endpoints on",
         "-- unnormalised rationals, each bound's theorem re-exported under `<id>-theorem` (a renamed or removed theorem",
         "-- fails this module), and for a bound on a table row its value inside.", "",
         "module Constants.Bounds where", "",
         "open import Data.Integer using (+_; -[1+_])",
         "open import Data.Rational.Unnormalised.Base using (ℚᵘ; mkℚᵘ; _≤_; _<_; *≤*; *<*)",
         "open import Data.Product using (_×_; _,_)",
         "open import Relation.Nullary.Decidable using (toWitness)",
         "import Data.Integer.Properties as ℤ", "import Constants.SI as SI"] + [f"import {m}" for m in mods] + [""]
    for b in bs:
        st = parity[b["theorem"]]
        mod = module_of(st["agda"]["file"], "Agda/", ".agda")
        L += bound_doc(b, st, "-- ", "-- ") + [
              f"open {mod} public using () renaming ({st['agda']['name']} to {b['id']}-theorem)"]
        for side in ("lower", "upper"):
            e = endpoint(b.get(side))
            if e:
                L += [f"{b['id']}-{side} : ℚᵘ", f"{b['id']}-{side} = {agda_q(e[0])}"]
        if b.get("row"):
            row = f"SI.{b['row']}"
            lo, hi = endpoint(b.get("lower")), endpoint(b.get("upper"))
            conj, prf = [], []
            if lo:
                conj.append(f"({b['id']}-lower {'<' if lo[1] else '≤'} {row})")
                prf.append("*<* (toWitness {a? = _ ℤ.<? _} _)" if lo[1] else "*≤* (toWitness {a? = _ ℤ.≤? _} _)")
            if hi:
                conj.append(f"({row} {'<' if hi[1] else '≤'} {b['id']}-upper)")
                prf.append("*<* (toWitness {a? = _ ℤ.<? _} _)" if hi[1] else "*≤* (toWitness {a? = _ ℤ.≤? _} _)")
            L += [f"{b['id']}-admits : {' × '.join(conj)}", f"{b['id']}-admits = {' , '.join(prf)}"]
        L.append("")
    return "\n".join(L)


def hs_q(v: Fraction) -> str:
    return f"({v.numerator} % {v.denominator})"


def haskell_bounds(table: dict, parity: dict[str, dict]) -> str:
    bs = bound_rows(table)
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", f"-- {HEADER}", "-- |",
         "-- The second-law bounds of the constants table (twin of Lean/Constants/Bounds.lean): exact endpoints, the",
         "-- theorem that proves each bound, and 'admits'. A bound fixes no value; the value stays cited, measured or",
         "-- chosen. 'boundChecks' lists each bound on a table row against the row's exact value.",
         "module UMST.Constants.Bounds where", "", "import Data.Ratio ((%))"]
    if any(b.get("row") for b in bs):
        L.append("import qualified UMST.Constants.SI as SI")
    L += ["", "-- | One endpoint: the exact value and whether the endpoint itself is excluded.",
          "data Endpoint = Endpoint { endpointAt :: Rational, endpointStrict :: Bool } deriving (Eq, Show)", "",
          "-- | A second-law bound: the interval a quantity must lie in and the theorem (Lean name) that proves it.",
          "data Bound = Bound", "  { boundId :: String", "  , boundSymbol :: String", "  , boundUnit :: Maybe String",
          "  , boundLower :: Maybe Endpoint", "  , boundUpper :: Maybe Endpoint", "  , boundTheorem :: String",
          "  , boundLanguages :: [String]", "  } deriving (Eq, Show)", "",
          "-- | Whether a value lies in the bound.", "admits :: Bound -> Rational -> Bool",
          "admits b v = maybe True above (boundLower b) && maybe True below (boundUpper b)", "  where",
          "    above (Endpoint a s) = if s then a < v else a <= v",
          "    below (Endpoint a s) = if s then v < a else v <= a", ""]
    for b in bs:
        st = parity[b["theorem"]]
        ep = lambda side: "Nothing" if not b.get(side) else \
            f"(Just (Endpoint {hs_q(endpoint(b[side])[0])} {endpoint(b[side])[1]}))"
        unit = "Nothing" if b.get("unit") is None else f"(Just {json.dumps(b['unit'], ensure_ascii=False)})"
        L += bound_doc(b, st, "-- | ", "-- ") + [
              f"{b['id']} :: Bound",
              f"{b['id']} = Bound {json.dumps(b['id'])} {json.dumps(b['symbol'], ensure_ascii=False)} {unit} "
              f"{ep('lower')} {ep('upper')}",
              f"  {json.dumps(b['theorem'])} {json.dumps(b['languages'])}", ""]
    L += ["-- | Every bound, in table order.", "bounds :: [Bound]", "bounds = [" + ", ".join(b["id"] for b in bs) + "]",
          "", "-- | Each bound on a table row against the row's exact value.", "boundChecks :: [(String, Bool)]"]
    rows = [f'("{b["id"]} admits {b["row"]}", admits {b["id"]} SI.{b["row"]})' for b in bs if b.get("row")]
    L += (["boundChecks =", "  [ " + "\n  , ".join(rows), "  ]", ""] if rows else ["boundChecks = []", ""])
    return "\n".join(L)


def haskell_bound_props(table: dict, parity: dict[str, dict]) -> str:
    bs = bound_rows(table)
    by_mod: dict[str, list[str]] = {}
    for b in bs:
        h = parity[b["theorem"]]["haskell"]
        names = by_mod.setdefault(module_of(h["file"], "Haskell/test/", ".hs"), [])
        if h["name"] not in names:
            names.append(h["name"])
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", f"-- {HEADER}",
         "-- | Each second-law bound of the constants table with the property that tests its theorem's statement",
         "-- (the Haskell column of formal_parity.json): a renamed or removed property fails this module.",
         "module ConstantsBoundsProps (boundProperties) where", "", "import Test.QuickCheck (Property)", ""]
    L += [f"import {m} ({', '.join(n)})" for m, n in sorted(by_mod.items())]
    L += ["", "-- | Bound id and property, in table order.", "boundProperties :: [(String, Property)]",
          "boundProperties ="]
    rows = [f'("{b["id"]}", {parity[b["theorem"]]["haskell"]["name"]})' for b in bs]
    L += ["  [ " + "\n  , ".join(rows), "  ]", ""]
    return "\n".join(L)


def rust_endpoint(e: tuple[Fraction, bool] | None, side: str) -> str:
    """`Some(Endpoint { … })` with the f64 rounded into the interval: up for a lower endpoint, down for an upper one,
    so `admits` never takes a value outside the exact bound."""
    if e is None:
        return "None"
    x = float(e[0])
    if side == "lower" and Fraction(x) < e[0]:
        x = math.nextafter(x, math.inf)
    if side == "upper" and Fraction(x) > e[0]:
        x = math.nextafter(x, -math.inf)
    return (f"Some(Endpoint {{\n        at: {rust_f64(Fraction(x))},\n        exact_num: \"{e[0].numerator}\",\n"
            f"        exact_den: \"{e[0].denominator}\",\n        strict: {str(e[1]).lower()},\n    }})")


def rust_bounds(table: dict, vals: dict[str, Fraction]) -> list[str]:
    bs = bound_rows(table)
    if not bs:
        return []
    parity = parity_statements()
    L = ["/// One endpoint of a bound: the exact rational, its `f64` rounded into the interval (up for a lower",
         "/// endpoint, down for an upper one, so `admits` never takes a value outside the exact bound), and whether",
         "/// the endpoint itself is excluded.", "#[derive(Clone, Copy, Debug, PartialEq)]", "pub struct Endpoint {",
         "    pub at: f64,", "    pub exact_num: &'static str,", "    pub exact_den: &'static str,", "    pub strict: bool,",
         "}", "",
         "/// A second-law bound: the interval a quantity must lie in and the theorem (a Lean name, with the languages",
         "/// formal_parity.json states it in) that proves it. A bound fixes no value; the value stays cited, measured",
         "/// or chosen.", "#[derive(Clone, Copy, Debug, PartialEq)]", "pub struct Bound {", "    pub id: &'static str,",
         "    pub symbol: &'static str,", "    /// `None` for a sign bound, the same in every unit.",
         "    pub unit: Option<&'static str>,", "    pub lower: Option<Endpoint>,", "    pub upper: Option<Endpoint>,",
         "    pub theorem: &'static str,", "    pub parity: &'static str,", "    pub languages: &'static [&'static str],",
         "}", "", "impl Bound {",
         "    /// Whether `v` lies in the bound; NaN never does. A `const fn`, so a consumer checks its value at compile",
         "    /// time: `const _: () = assert!(umst_constants::X_BOUND.admits(V));`.",
         "    pub const fn admits(&self, v: f64) -> bool {", "        if v.is_nan() {", "            return false;",
         "        }", "        let above = match self.lower {", "            Some(e) if e.strict => v > e.at,",
         "            Some(e) => v >= e.at,", "            None => true,", "        };",
         "        let below = match self.upper {", "            Some(e) if e.strict => v < e.at,",
         "            Some(e) => v <= e.at,", "            None => true,", "        };", "        above && below", "    }",
         "}", ""]
    for b in bs:
        st = parity[b["theorem"]]
        unit = "None" if b.get("unit") is None else f'Some("{b["unit"]}")'
        langs = ", ".join(f'"{x}"' for x in b["languages"])
        L += bound_doc(b, st, "/// ", "/// ", width=100) + [
              f"pub const {rust_name(b['id'])}_BOUND: Bound = Bound {{", f'    id: "{b["id"]}",',
              f'    symbol: "{b["symbol"]}",', f"    unit: {unit},",
              f"    lower: {rust_endpoint(endpoint(b.get('lower')), 'lower')},",
              f"    upper: {rust_endpoint(endpoint(b.get('upper')), 'upper')},", f'    theorem: "{b["theorem"]}",',
              f'    parity: "{st["id"]}",', f"    languages: &[{langs}],", "};", ""]
    for b in bs:
        if b.get("row"):
            one = f"const _: () = assert!({rust_name(b['id'])}_BOUND.admits({rust_name(b['row'])}));"
            body = [one] if len(one) <= 100 else ["const _: () = assert!(",
                                                  f"    {rust_name(b['id'])}_BOUND.admits({rust_name(b['row'])})", ");"]
            L += [f"/// The table's {b['row']} lies in its bound, checked at compile time."] + body + [""]
    L += ["/// Every bound, in table order.", "pub const BOUNDS: &[Bound] = &["]
    L += [f"    {rust_name(b['id'])}_BOUND," for b in bs]
    L += ["];", ""]
    return L


# ------------------------------------------------------------------------------------------------- README table

SUP = str.maketrans("-0123456789", "⁻⁰¹²³⁴⁵⁶⁷⁸⁹")


def terminating(v: Fraction) -> bool:
    d = v.denominator
    for p in (2, 5):
        while d % p == 0:
            d //= p
    return d == 1


def scientific(v: Fraction, digits: int | None = None) -> str:
    """`m × 10ⁿ` with every significant digit of a terminating value, or `digits` digits otherwise."""
    if v == 0:
        return "0"
    sign = "-" if v < 0 else ""
    v = abs(v)
    exp = len(str(v.numerator)) - len(str(v.denominator))
    if v < Fraction(10) ** exp:
        exp -= 1
    m = v / Fraction(10) ** exp
    if digits is None:
        text = ""
        while m != 0 and len(text) < 40:
            d = m.numerator // m.denominator
            text += str(d)
            m = (m - d) * 10
    else:
        q = round(m * 10 ** (digits - 1))
        if q >= 10 ** digits:
            q //= 10
            exp += 1
        text = str(q).rstrip("0") or "0"
    mant = text[0] + ("." + text[1:] if len(text) > 1 else "")
    return f"{sign}{mant}" if exp == 0 else f"{sign}{mant} × 10{str(exp).translate(SUP)}"


def shown(v: Fraction) -> str:
    return scientific(v) if terminating(v) else "≈ " + scientific(v, 12)


def readme(table: dict, vals: dict[str, Fraction]) -> str:
    rows = ["| Symbol | Constant | Kind | Value | Unit | Derivation or authority | Proved by |",
            "|---|---|---|---|---|---|---|"]
    used, links = set(), []
    for c in table["constants"]:
        if c["fibre"] not in ("both", FIBRE):
            continue
        v = vals[c["id"]]
        if c["status"] == "measured":
            value = f"{scientific(v)} ± {scientific(frac(c, 'uncertainty_'))}"
        else:
            value = shown(v) + (" (exact)" if terminating(v) else "")
        if c["status"] == "derived":
            how = f"`{c['formula']}`"
            proof = f"`{c['id']}_value`" + (f", `{c['id']}_derivation`" if split(c)[1] else "") + (
                f", `{c['id']}_within_{c['crosscheck']['authority']}`" if "crosscheck" in c else "")
            if "crosscheck" in c:
                used.add(c["crosscheck"]["authority"])
        elif c["status"] == "policy":
            how = f"model choice: {c['reason']}; range [{c['range']['low']}, {c['range']['high']}]"
            proof = f"`{c['id']}_in_range`"
        else:
            how = c["authority"]
            used.add(c["authority"])
            proof = "a definition (cited)" if c["status"] == "cited" else "a definition with its uncertainty (cited)"
        rows.append(f"| {c['symbol']} | {c['name']} | {c['status']} | {value} | {c['unit']} | {how} | {proof} |")
        if c.get("second_law"):
            links.append(f"- {c['symbol']}: {c['second_law']}.")
    out = rows + [""] + [f"- {a}: {table['authorities'][a]}." for a in sorted(used)]
    if links:
        out += ["", "Where these constants enter the second law:", ""] + links
    if any(r.split(" | ")[3].startswith("≈") for r in rows[2:]):
        out += ["", "Values marked ≈ are shown to twelve significant digits; the modules hold them as exact rationals."]
    return "\n".join(out)


def outputs() -> dict[str, str]:
    table = load()
    vals = values(table)
    parity = parity_statements() if bound_rows(table) else {}
    problems = bound_problems(table, vals, parity) if bound_rows(table) else []
    if problems:
        raise SystemExit("FAIL: constants/constants.json bounds:\n  " + "\n  ".join(problems))
    out = {}
    if REPO == HOME:
        out["Lean/Constants/SI.lean"] = lean(table, vals)
        out["constants-rs/src/lib.rs"] = rust(table, vals)
    out["Coq/Constants/SI.v"] = coq(table, vals)
    out["Agda/Constants/SI.agda"] = agda(table, vals)
    hs = "Haskell/UMST/Constants/SI.hs" if REPO == HOME else "Haskell/src/UMST/Constants/SI.hs"
    out[hs] = haskell(table, vals)
    if bound_rows(table):
        out["Lean/Constants/Bounds.lean"] = lean_bounds(table, parity)
        out["Coq/Constants/Bounds.v"] = coq_bounds(table, parity)
        out["Agda/Constants/Bounds.agda"] = agda_bounds(table, parity)
        out["Haskell/UMST/Constants/Bounds.hs"] = haskell_bounds(table, parity)
        out["Haskell/test/ConstantsBoundsProps.hs"] = haskell_bound_props(table, parity)
    return out


def replace_block(text: str, body: str) -> str:
    return re.sub(r"(<!-- constants:begin -->\n).*?(<!-- constants:end -->)", lambda m: m.group(1) + body + "\n" + m.group(2),
                  text, flags=re.S)


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    files = outputs()
    for rel, text in files.items():
        path = os.path.join(ROOT, rel)
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old != text:
            stale.append(rel)
            if not check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "w", encoding="utf-8") as f:
                    f.write(text)
    table = load()
    block = readme(table, values(table))
    rpath = os.path.join(ROOT, "README.md")
    rtext = open(rpath, encoding="utf-8").read()
    if "<!-- constants:begin -->" in rtext:
        new = replace_block(rtext, block)
        if new != rtext:
            stale.append("README.md")
            if not check:
                open(rpath, "w", encoding="utf-8").write(new)
    elif check:
        stale.append("README.md (no constants block)")
    if check and stale:
        print("FAIL: generated constants are stale: " + ", ".join(stale) + " (run scripts/gen_constants.py)",
              file=sys.stderr)
        return 1
    print(("OK: constants are current" if check else "wrote: " + ", ".join(stale or ["nothing changed"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
