#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
# SPDX-License-Identifier: MIT
"""Generate the ground-state modules from chemistry/ground_states.json (cited NIST ASD data), in four languages.

Each NIST configuration lists the valence subshells; the full occupancy is the noble-gas core followed by the
period's omitted subshells filled completely, in Madelung order, until the electron count equals Z. A partial fill,
an unknown subshell or a count that does not reach Z is an error: the data, not this script, decides every
occupancy.

Every language receives the cited occupancies, the Madelung order (subshells by n + ℓ, then n), the computed Madelung
configuration of any Z, and the same theorems, decided by computation:

  capacity           derived, for every ℓ and n: the one-electron states of a subshell are the pairs (j, spin) with
                     j = m_ℓ + ℓ < 2ℓ + 1, without repetition, so a subshell holds 2(2ℓ + 1) electrons and shell n
                     holds Σ_{ℓ<n} 2(2ℓ + 1) = 2n² (2, 8, 18, 32, …)
  madelung order     sorted by (n + ℓ, n) and complete up to 7p
  electron count     every computed configuration for Z ≤ 118 holds exactly Z electrons; every cited one holds its Z
  within capacity    no subshell holds more than its capacity, computed or cited
  exceptions         the elements whose cited ground state differs from the Madelung prediction are exactly the
                     computed list (twenty: Cr … Lr)

`--check` regenerates in memory and fails on any difference.
"""
from __future__ import annotations

import json
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SPDX = "SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar"
HEADER = "Generated by scripts/gen_ground_states.py from chemistry/ground_states.json; edit the data, not this file."
LETTERS = "spdf"
ORDER = sorted(((n, l) for n in range(1, 8) for l in range(0, min(n, 4))), key=lambda s: (s[0] + s[1], s[0]))
NOBLE = [2, 10, 18, 36, 54, 86]
ZMAX = 118


def capacity(s: tuple[int, int]) -> int:
    return 2 * (2 * s[1] + 1)


def madelung(z: int) -> list[tuple[int, int, int]]:
    out, left = [], z
    for s in ORDER:
        if left <= 0:
            break
        k = min(capacity(s), left)
        out.append((s[0], s[1], k))
        left -= k
    return out


def expand(z: int, config: str) -> list[tuple[int, int, int]]:
    listed: dict[tuple[int, int], int] = {}
    for part in config.split("."):
        if part.startswith("("):
            continue  # an intermediate coupling term, not an occupancy
        m = re.fullmatch(r"(\d)([spdf])(\d*)", part)
        if not m:
            raise SystemExit(f"Z={z}: cannot read subshell {part!r} in {config!r}")
        listed[(int(m.group(1)), LETTERS.index(m.group(2)))] = int(m.group(3) or 1)
    core = max((g for g in NOBLE if g < z), default=0)
    occ = {(n, l): k for n, l, k in madelung(core)}
    occ.update(listed)
    deficit = z - sum(occ.values())
    for s in ORDER:
        if deficit <= 0:
            break
        if s in occ:
            continue
        if capacity(s) > deficit:
            raise SystemExit(f"Z={z}: {config!r} would need a partial fill of {s}")
        occ[s] = capacity(s)
        deficit -= capacity(s)
    if deficit != 0:
        raise SystemExit(f"Z={z}: {config!r} leaves {deficit} electrons unplaced")
    return [(n, l, occ[(n, l)]) for n, l in ORDER if occ.get((n, l), 0) > 0]


def load():
    with open(os.path.join(ROOT, "chemistry/ground_states.json"), encoding="utf-8") as f:
        doc = json.load(f)
    atoms = [(a["z"], a["symbol"], expand(a["z"], a["nist_configuration"])) for a in doc["atoms"]]
    exceptions = [z for z, _, occ in atoms if occ != madelung(z)]
    return doc, atoms, exceptions


def triples(occ, fmt):
    return ", ".join(fmt.format(n=n, l=l, k=k) for n, l, k in occ)


# --------------------------------------------------------------------------------------------------- Lean

def lean(doc, atoms, exceptions) -> str:
    src = doc["source"]
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", "/-", f"  {HEADER}", "",
         "  Ground-state electron configurations of the neutral atoms Z = 1 … 103, cited from the NIST Atomic Spectra",
         f"  Database ({src['retrieved']}; SHA-256 of the response {src['sha256_of_response']}), and the Madelung",
         "  (n + ℓ, then n) prediction, computed. A configuration is a list of (n, ℓ, occupancy) in Madelung order.",
         "  The capacity of a subshell is derived from its one-electron states.", "-/", "",
         "namespace UMST.Chem.GroundStates", "",
         "/-- Electrons a subshell (n, ℓ) holds when full: 2(2ℓ + 1), the number of its states (`capacity_eq_length`). -/",
         "def capacity (s : Nat × Nat)  : Nat := 2 * (2 * s.2 + 1)", "",
         "/-- The one-electron states of a subshell with azimuthal number ℓ: the magnetic number m_ℓ = j − ℓ with",
         "    j < 2ℓ + 1, and the spin projection (down or up). -/",
         "def states (l : Nat) : List (Nat × Bool) :=",
         "  ((List.range (2 * l + 1)).map fun j => (j, false)) ++ ((List.range (2 * l + 1)).map fun j => (j, true))", "",
         "/-- A pair is a state exactly when −ℓ ≤ m_ℓ ≤ ℓ. -/",
         "theorem mem_states (l j : Nat) (s : Bool) : (j, s) ∈ states l ↔ j < 2 * l + 1 := by",
         "  simp only [states, List.mem_append, List.mem_map, List.mem_range, Prod.mk.injEq]",
         "  cases s <;> constructor <;> intro h",
         "  all_goals first",
         "    | (rcases h with ⟨i, hi, rfl, _⟩ | ⟨i, hi, rfl, _⟩ <;> first | exact hi | simp_all)",
         "    | exact Or.inl ⟨j, h, rfl, rfl⟩",
         "    | exact Or.inr ⟨j, h, rfl, rfl⟩", "",
         "/-- No state is listed twice. -/",
         "theorem states_nodup (l : Nat) : (states l).Nodup := by",
         "  unfold states List.Nodup",
         "  rw [List.pairwise_append]",
         "  refine ⟨(List.nodup_range _).map _ (fun a b h e => h (by simp at e; omega)),",
         "          (List.nodup_range _).map _ (fun a b h e => h (by simp at e; omega)), ?_⟩",
         "  intro a ha b hb hab",
         "  simp only [List.mem_map] at ha hb",
         "  obtain ⟨i, _, rfl⟩ := ha",
         "  obtain ⟨j, _, rfl⟩ := hb",
         "  simp at hab", "",
         "/-- The capacity of a subshell is the number of its states. -/",
         "theorem capacity_eq_length (n l : Nat) : capacity (n, l) = (states l).length := by",
         "  simp [states, capacity]; omega", "",
         "/-- Electrons shell n holds when full: the capacities of its subshells ℓ < n. -/",
         "def shellCapacity (n : Nat) : Nat := ((List.range n).map fun l => capacity (n, l)).foldr (· + ·) 0", "",
         "theorem foldr_add_shift (xs : List Nat) (c : Nat) : xs.foldr (· + ·) c = xs.foldr (· + ·) 0 + c := by",
         "  induction xs with",
         "  | nil => simp",
         "  | cons x xs ih => simp only [List.foldr_cons, ih]; omega", "",
         "/-- Shell n holds 2n² electrons. -/",
         "theorem shellCapacity_eq (n : Nat) : shellCapacity n = 2 * (n * n) := by",
         "  unfold shellCapacity",
         "  induction n with",
         "  | zero => rfl",
         "  | succ k ih =>",
         "    rw [List.range_succ, List.map_append, List.foldr_append, foldr_add_shift]",
         "    simp only [capacity, List.map_cons, List.map_nil, List.foldr_cons, List.foldr_nil] at ih ⊢",
         "    have e : (k + 1) * (k + 1) = k * k + 2 * k + 1 := by",
         "      simp only [Nat.add_mul, Nat.mul_add, Nat.mul_one, Nat.one_mul]; omega",
         "    rw [ih, e]; omega", "",
         "/-- Madelung rank: subshells fill by n + ℓ, then by n (n ≤ 7 < 8). -/",
         "def madelungRank (s : Nat × Nat)  : Nat := (s.1 + s.2) * 8 + s.1", "",
         "/-- Subshells 1s … 7p in Madelung order. -/",
         "def madelungOrder : List (Nat × Nat) :=",
         "  [" + ", ".join(f"({n}, {l})" for n, l in ORDER) + "]", "",
         "theorem madelungOrder_sorted : madelungOrder.Pairwise (fun a b => madelungRank a < madelungRank b) := by",
         "  decide", "",
         "/-- Every subshell with 1 ≤ n ≤ 7 and ℓ < min(n, 4) appears. -/",
         "theorem madelungOrder_complete :",
         "    ((List.range 8).all fun n => (List.range 4).all fun l =>",
         "      !(1 ≤ n && l < n) || madelungOrder.contains (n, l)) = true := by",
         "  decide", "",
         "/-- Fill subshells in order until `z` electrons are placed. -/",
         "def fill : List (Nat × Nat) → Nat → List (Nat × Nat × Nat)",
         "  | [], _ => []",
         "  | _, 0 => []",
         "  | s :: rest, z + 1 =>",
         "    let k := min (capacity s) (z + 1)",
         "    (s.1, s.2, k) :: fill rest (z + 1 - k)", "",
         "/-- The Madelung prediction for `z` electrons. -/",
         "def madelung (z   : Nat) : List (Nat × Nat × Nat) := fill madelungOrder z", "",
         "/-- Electrons in a configuration. -/",
         "def electrons (c : List (Nat × Nat × Nat))  : Nat := (c.map fun x => x.2.2).sum", "",
         "/-- No subshell above its capacity. -/",
         "def withinCapacity (c : List (Nat × Nat × Nat)) : Bool := c.all fun x => x.2.2 ≤ capacity (x.1, x.2.1)", "",
         "set_option maxHeartbeats 4000000 in",
         "/-- Cited ground states (NIST ASD), expanded to full occupancies. -/",
         "def observed : List (Nat × List (Nat × Nat × Nat)) := ["]
    L += [f"  ({z}, [{triples(occ, '({n}, {l}, {k})')}])" + ("," if i < len(atoms) - 1 else "")
          for i, (z, _, occ) in enumerate(atoms)]
    L += ["]", "",
          f"theorem madelung_electrons_check : (List.range {ZMAX + 1}).all (fun z => electrons (madelung z) == z) = true := by",
          "  decide", "",
          f"/-- Every Madelung configuration for Z ≤ {ZMAX} holds exactly Z electrons. -/",
          f"theorem madelung_electrons (z : Nat) (hz : z ≤ {ZMAX}) : electrons (madelung z) = z := by",
          "  have h := List.all_eq_true.mp madelung_electrons_check z (List.mem_range.mpr (by omega))",
          "  simpa using h", "",
          f"theorem madelung_withinCapacity_check : (List.range {ZMAX + 1}).all (fun z => withinCapacity (madelung z)) = true := by",
          "  decide", "",
          f"/-- No Madelung configuration for Z ≤ {ZMAX} puts more than 2(2ℓ + 1) electrons in a subshell. -/",
          f"theorem madelung_withinCapacity (z : Nat) (hz : z ≤ {ZMAX}) : withinCapacity (madelung z) = true :=",
          "  List.all_eq_true.mp madelung_withinCapacity_check z (List.mem_range.mpr (by omega))", "",
          "theorem observed_atomic_numbers : observed.map Prod.fst = List.range' 1 " + str(len(atoms)) + " := by",
          "  decide", "",
          "theorem observed_electrons : observed.all (fun e => electrons e.2 == e.1) = true := by",
          "  decide", "",
          "theorem observed_withinCapacity : observed.all (fun e => withinCapacity e.2) = true := by",
          "  decide", "",
          "/-- The elements whose cited ground state differs from the Madelung prediction. -/",
          "theorem madelung_exceptions :",
          "    (observed.filter fun e => e.2 != madelung e.1).map Prod.fst =",
          "      [" + ", ".join(map(str, exceptions)) + "] := by",
          "  decide", "",
          "end UMST.Chem.GroundStates", ""]
    return "\n".join(L)


# --------------------------------------------------------------------------------------------------- Coq

def coq(doc, atoms, exceptions) -> str:
    src = doc["source"]
    L = [f"(* {SPDX} *)", "(* SPDX-License-Identifier: MIT *)", f"(* {HEADER} *)",
         "(* Ground states Z = 1 … 103 cited from the NIST Atomic Spectra Database                              *)",
         f"(* ({src['retrieved']}; SHA-256 {src['sha256_of_response'][:32]}…), the Madelung prediction computed;       *)",
         "(* twin of Lean/Chem/GroundStates.lean. Zero Axiom, Parameter or Admitted.                              *)", "",
         "From Stdlib Require Import List Arith Lia Bool FinFun.", "Import ListNotations.", "",
         "Definition capacity (s : nat * nat) : nat := 2 * (2 * snd s + 1).", "",
         "(* The one-electron states of a subshell: m_l = j - l with j < 2l + 1, spin down or up. *)",
         "Definition states (l : nat) : list (nat * bool) :=",
         "  map (fun j => (j, false)) (seq 0 (2 * l + 1)) ++ map (fun j => (j, true)) (seq 0 (2 * l + 1)).", "",
         "Lemma in_states (l j : nat) (s : bool) : In (j, s) (states l) <-> j < 2 * l + 1.",
         "Proof.",
         "  unfold states. rewrite in_app_iff, !in_map_iff. split.",
         "  - intros [[x [Hx Hin]] | [x [Hx Hin]]]; inversion Hx; subst; apply in_seq in Hin; lia.",
         "  - intro H. destruct s.",
         "    + right. exists j. split; [reflexivity | apply in_seq; lia].",
         "    + left. exists j. split; [reflexivity | apply in_seq; lia].",
         "Qed.", "",
         "Lemma states_nodup (l : nat) : NoDup (states l).",
         "Proof.",
         "  unfold states. apply NoDup_app.",
         "  - apply Injective_map_NoDup; [intros a b H; now inversion H | apply seq_NoDup].",
         "  - apply Injective_map_NoDup; [intros a b H; now inversion H | apply seq_NoDup].",
         "  - intros x Hx Hy. apply in_map_iff in Hx as [a [Ha _]]. apply in_map_iff in Hy as [b [Hb _]].",
         "    subst. discriminate.",
         "Qed.", "",
         "Lemma capacity_eq_length (n l : nat) : capacity (n, l) = length (states l).",
         "Proof. unfold capacity, states. simpl. rewrite length_app, !length_map, length_seq. lia. Qed.", "",
         "Definition shellCapacity (n : nat) : nat := fold_right Nat.add 0 (map (fun l => capacity (n, l)) (seq 0 n)).", "",
         "Lemma fold_add_shift (xs : list nat) (c : nat) : fold_right Nat.add c xs = fold_right Nat.add 0 xs + c.",
         "Proof. induction xs as [| x xs IH]; simpl; [reflexivity | rewrite IH; lia]. Qed.", "",
         "Lemma shellCapacity_eq (n : nat) : shellCapacity n = 2 * (n * n).",
         "Proof.",
         "  unfold shellCapacity, capacity. simpl. induction n as [| k IH]; [reflexivity |].",
         "  rewrite seq_S, map_app, fold_right_app, fold_add_shift. simpl. rewrite IH. lia.",
         "Qed.", "",
         "Definition madelungRank (s : nat * nat) : nat := (fst s + snd s) * 8 + fst s.", "",
         "Definition madelungOrder : list (nat * nat) :=",
         "  [" + "; ".join(f"({n}, {l})" for n, l in ORDER) + "].", "",
         "Fixpoint sortedB (l : list (nat * nat)) : bool :=",
         "  match l with",
         "  | a :: ((b :: _) as rest) => Nat.ltb (madelungRank a) (madelungRank b) && sortedB rest",
         "  | _ => true",
         "  end.",
         "Lemma madelungOrder_sorted : sortedB madelungOrder = true.",
         "Proof. vm_compute. reflexivity. Qed.", "",
         "Fixpoint fill (order : list (nat * nat)) (z : nat) : list (nat * nat * nat) :=",
         "  match order, z with",
         "  | [], _ => []",
         "  | _, 0 => []",
         "  | s :: rest, S z' => let k := Nat.min (capacity s) z in (fst s, snd s, k) :: fill rest (z - k)",
         "  end.",
         "Definition madelung (z : nat) : list (nat * nat * nat) := fill madelungOrder z.",
         "Definition electrons (c : list (nat * nat * nat)) : nat := fold_right (fun x acc => snd x + acc) 0 c.",
         "Definition withinCapacity (c : list (nat * nat * nat)) : bool :=",
         "  forallb (fun x => Nat.leb (snd x) (capacity (fst (fst x), snd (fst x)))) c.",
         "Fixpoint configEqb (a b : list (nat * nat * nat)) : bool :=",
         "  match a, b with",
         "  | [], [] => true",
         "  | (n1, l1, k1) :: r1, (n2, l2, k2) :: r2 => Nat.eqb n1 n2 && Nat.eqb l1 l2 && Nat.eqb k1 k2 && configEqb r1 r2",
         "  | _, _ => false",
         "  end.", "",
         "Definition observed : list (nat * list (nat * nat * nat)) := ["]
    L += [f"  ({z}, [{triples(occ, '({n}, {l}, {k})').replace(', (', '; (')}])" + (";" if i < len(atoms) - 1 else "")
          for i, (z, _, occ) in enumerate(atoms)]
    L += ["].", "",
          f"Lemma madelung_electrons_check : forallb (fun z => Nat.eqb (electrons (madelung z)) z) (seq 0 {ZMAX + 1}) = true.",
          "Proof. vm_compute. reflexivity. Qed.",
          f"Lemma madelung_electrons (z : nat) : z <= {ZMAX} -> electrons (madelung z) = z.",
          "Proof.",
          "  intro Hz. apply Nat.eqb_eq.",
          "  apply (proj1 (forallb_forall _ _) madelung_electrons_check).",
          "  apply in_seq. lia.",
          "Qed.",
          f"Lemma madelung_withinCapacity_check : forallb (fun z => withinCapacity (madelung z)) (seq 0 {ZMAX + 1}) = true.",
          "Proof. vm_compute. reflexivity. Qed.",
          "Lemma observed_atomic_numbers : map fst observed = seq 1 " + str(len(atoms)) + ".",
          "Proof. vm_compute. reflexivity. Qed.",
          "Lemma observed_electrons : forallb (fun e => Nat.eqb (electrons (snd e)) (fst e)) observed = true.",
          "Proof. vm_compute. reflexivity. Qed.",
          "Lemma observed_withinCapacity : forallb (fun e => withinCapacity (snd e)) observed = true.",
          "Proof. vm_compute. reflexivity. Qed.",
          "Lemma madelung_exceptions :",
          "  map fst (filter (fun e => negb (configEqb (snd e) (madelung (fst e)))) observed) =",
          "    [" + "; ".join(map(str, exceptions)) + "].",
          "Proof. vm_compute. reflexivity. Qed.", ""]
    return "\n".join(L)


# --------------------------------------------------------------------------------------------------- Agda

def agda(doc, atoms, exceptions) -> str:
    src = doc["source"]
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", f"-- {HEADER}",
         f"-- Ground states Z = 1 … 103 cited from the NIST Atomic Spectra Database ({src['retrieved']}); the Madelung",
         "-- prediction computed; every check holds by `refl`. Twin of Lean/Chem/GroundStates.lean.", "",
         "{-# OPTIONS --without-K --safe #-}", "", "module Chem.GroundStates where", "",
         "open import Data.Bool using (Bool; true; false; _∧_; not)",
         "open import Data.Empty using (⊥)",
         "open import Data.List using (List; []; _∷_; map; filterᵇ; upTo; foldr; _++_; length; [_])",
         "open import Data.List.Properties using (length-++; length-map; length-upTo; upTo-∷ʳ; map-++)",
         "open import Data.List.Membership.Propositional using (_∈_)",
         "open import Data.List.Membership.Propositional.Properties",
         "  using (∈-++⁺ˡ; ∈-++⁺ʳ; ∈-++⁻; ∈-map⁺; ∈-map⁻; ∈-upTo⁺; ∈-upTo⁻)",
         "open import Data.List.Relation.Unary.Unique.Propositional using (Unique)",
         "import Data.List.Relation.Unary.Unique.Propositional.Properties as Unique",
         "open import Data.Nat using (ℕ; zero; suc; _+_; _*_; _∸_; _⊓_; _≡ᵇ_; _<ᵇ_; _≤ᵇ_; _<_)",
         "open import Data.Nat.ListAction using (sum)",
         "open import Data.Nat.ListAction.Properties using (sum-++)",
         "open import Data.Nat.Properties using (+-identityʳ)",
         "open import Data.Nat.Tactic.RingSolver using (solve-∀)",
         "open import Data.Product using (_×_; _,_; proj₁; proj₂)",
         "open import Data.Sum using (inj₁; inj₂)",
         "open import Function using (_∘_)",
         "open import Relation.Binary.PropositionalEquality using (_≡_; refl; sym; trans; cong; cong₂)", "",
         "allᵇ : {A : Set} → (A → Bool) → List A → Bool",
         "allᵇ p = foldr (λ x acc → p x ∧ acc) true", "",
         "Subshell : Set", "Subshell = ℕ × ℕ", "", "Occupancy : Set", "Occupancy = ℕ × ℕ × ℕ", "",
         "capacity : Subshell → ℕ", "capacity (_ , l) = 2 * (2 * l + 1)", "",
         "-- The one-electron states of a subshell: m_ℓ = j ∸ ℓ with j < 2ℓ + 1, spin down or up.",
         "State : Set", "State = ℕ × Bool", "",
         "states : ℕ → List State",
         "states l = map (λ j → j , false) (upTo (2 * l + 1)) ++ map (λ j → j , true) (upTo (2 * l + 1))", "",
         "∈-states⁺ : ∀ {l j} s → j < 2 * l + 1 → (j , s) ∈ states l",
         "∈-states⁺ false h = ∈-++⁺ˡ (∈-map⁺ (λ j → j , false) (∈-upTo⁺ h))",
         "∈-states⁺ {l} true h = ∈-++⁺ʳ (map (λ j → j , false) (upTo (2 * l + 1))) (∈-map⁺ (λ j → j , true) (∈-upTo⁺ h))", "",
         "∈-states⁻ : ∀ {l j s} → (j , s) ∈ states l → j < 2 * l + 1",
         "∈-states⁻ {l} p with ∈-++⁻ (map (λ j → j , false) (upTo (2 * l + 1))) p",
         "... | inj₁ q with ∈-map⁻ (λ j → j , false) q",
         "...   | _ , x∈ , refl = ∈-upTo⁻ x∈",
         "∈-states⁻ {l} p | inj₂ q with ∈-map⁻ (λ j → j , true) q",
         "...   | _ , x∈ , refl = ∈-upTo⁻ x∈", "",
         "states-unique : ∀ l → Unique (states l)",
         "states-unique l = Unique.++⁺ (Unique.map⁺ (cong proj₁) (Unique.upTo⁺ _)) (Unique.map⁺ (cong proj₁) (Unique.upTo⁺ _))",
         "  disjoint",
         "  where",
         "  disjoint : ∀ {v} → (v ∈ map (λ j → j , false) (upTo (2 * l + 1)) × v ∈ map (λ j → j , true) (upTo (2 * l + 1))) → ⊥",
         "  disjoint (p , q) with ∈-map⁻ (λ j → j , false) p | ∈-map⁻ (λ j → j , true) q",
         "  ... | _ , _ , refl | _ , _ , ()", "",
         "capacity-states : ∀ n l → capacity (n , l) ≡ length (states l)",
         "capacity-states n l = sym (trans (length-++ (map (λ j → j , false) (upTo k)))",
         "  (trans (cong₂ _+_ (trans (length-map _ (upTo k)) (length-upTo k)) (trans (length-map _ (upTo k)) (length-upTo k)))",
         "         (cong (k +_) (sym (+-identityʳ k)))))",
         "  where k = 2 * l + 1", "",
         "shellCapacity : ℕ → ℕ",
         "shellCapacity n = sum (map (λ l → capacity (n , l)) (upTo n))", "",
         "shell-step : ∀ n → 2 * (n * n) + (2 * (2 * n + 1) + 0) ≡ 2 * (suc n * suc n)",
         "shell-step = solve-∀", "",
         "shell-capacity : ∀ n → shellCapacity n ≡ 2 * (n * n)",
         "shell-capacity zero = refl",
         "shell-capacity (suc n) =",
         "  trans (cong (sum ∘ map c) (sym (upTo-∷ʳ n)))",
         "  (trans (cong sum (map-++ c (upTo n) [ n ]))",
         "  (trans (sum-++ (map c (upTo n)) [ c n ])",
         "  (trans (cong (_+ (c n + 0)) (shell-capacity n)) (shell-step n))))",
         "  where c = λ l → capacity (n , l)", "",
         "madelungRank : Subshell → ℕ", "madelungRank (n , l) = (n + l) * 8 + n", "",
         "madelungOrder : List Subshell",
         "madelungOrder = " + " ∷ ".join(f"({n} , {l})" for n, l in ORDER) + " ∷ []", "",
         "sortedᵇ : List Subshell → Bool",
         "sortedᵇ (a ∷ b ∷ rest) = (madelungRank a <ᵇ madelungRank b) ∧ sortedᵇ (b ∷ rest)",
         "sortedᵇ _ = true", "",
         "madelungOrder-sorted : sortedᵇ madelungOrder ≡ true", "madelungOrder-sorted = refl", "",
         "fill : List Subshell → ℕ → List Occupancy",
         "fill [] _ = []", "fill (_ ∷ _) zero = []",
         "fill ((n , l) ∷ rest) (suc z) = (n , l , k) ∷ fill rest (suc z ∸ k)",
         "  where k = capacity (n , l) ⊓ suc z", "",
         "madelung : ℕ → List Occupancy", "madelung = fill madelungOrder", "",
         "electrons : List Occupancy → ℕ", "electrons = foldr (λ x acc → proj₂ (proj₂ x) + acc) 0", "",
         "withinCapacity : List Occupancy → Bool",
         "withinCapacity = allᵇ (λ where (n , l , k) → k ≤ᵇ capacity (n , l))", "",
         "configᵇ : List Occupancy → List Occupancy → Bool",
         "configᵇ [] [] = true",
         "configᵇ ((n₁ , l₁ , k₁) ∷ r₁) ((n₂ , l₂ , k₂) ∷ r₂) = (n₁ ≡ᵇ n₂) ∧ (l₁ ≡ᵇ l₂) ∧ (k₁ ≡ᵇ k₂) ∧ configᵇ r₁ r₂",
         "configᵇ _ _ = false", "",
         "observed : List (ℕ × List Occupancy)", "observed ="]
    L += [f"  ({z} , {(' ∷ '.join(f'({n} , {l} , {k})' for n, l, k in occ)) + ' ∷ []'}) ∷" for z, _, occ in atoms]
    L += ["  []", "",
          f"madelung-electrons : allᵇ (λ z → electrons (madelung z) ≡ᵇ z) (upTo {ZMAX + 1}) ≡ true",
          "madelung-electrons = refl", "",
          f"madelung-withinCapacity : allᵇ (λ z → withinCapacity (madelung z)) (upTo {ZMAX + 1}) ≡ true",
          "madelung-withinCapacity = refl", "",
          "observed-electrons : allᵇ (λ e → electrons (proj₂ e) ≡ᵇ proj₁ e) observed ≡ true",
          "observed-electrons = refl", "",
          "observed-withinCapacity : allᵇ (λ e → withinCapacity (proj₂ e)) observed ≡ true",
          "observed-withinCapacity = refl", "",
          "madelung-exceptions :",
          "  map proj₁ (filterᵇ (λ e → not (configᵇ (proj₂ e) (madelung (proj₁ e)))) observed) ≡",
          "    " + " ∷ ".join(map(str, exceptions)) + " ∷ []",
          "madelung-exceptions = refl", ""]
    return "\n".join(L)


# --------------------------------------------------------------------------------------------------- Haskell

def haskell(doc, atoms, exceptions) -> str:
    src = doc["source"]
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", f"-- {HEADER}", "-- |",
         f"-- Ground states Z = 1 … 103 cited from the NIST Atomic Spectra Database ({src['retrieved']}); the Madelung",
         "-- prediction computed. Twin of Lean/Chem/GroundStates.lean; 'checks' lists the statements every language",
         "-- proves, and the test suite runs them.",
         "module UMST.Chem.GroundStates where", "",
         "import Data.List (nub, sort)", "",
         "type Occupancy = (Int, Int, Int)", "",
         "capacity :: (Int, Int) -> Int", "capacity (_, l) = 2 * (2 * l + 1)", "",
         "-- | The one-electron states of a subshell: m_l = j - l with j < 2l + 1, spin down or up.",
         "states :: Int -> [(Int, Bool)]",
         "states l = [(j, False) | j <- [0 .. 2 * l]] ++ [(j, True) | j <- [0 .. 2 * l]]", "",
         "shellCapacity :: Int -> Int",
         "shellCapacity n = sum [capacity (n, l) | l <- [0 .. n - 1]]", "",
         "madelungRank :: (Int, Int) -> Int", "madelungRank (n, l) = (n + l) * 8 + n", "",
         "madelungOrder :: [(Int, Int)]",
         "madelungOrder = [" + ", ".join(f"({n}, {l})" for n, l in ORDER) + "]", "",
         "fill :: [(Int, Int)] -> Int -> [Occupancy]",
         "fill [] _ = []",
         "fill ((n, l) : rest) z",
         "  | z <= 0 = []",
         "  | otherwise = let k = min (capacity (n, l)) z in (n, l, k) : fill rest (z - k)", "",
         "madelung :: Int -> [Occupancy]", "madelung = fill madelungOrder", "",
         "electrons :: [Occupancy] -> Int", "electrons c = sum [k | (_, _, k) <- c]", "",
         "withinCapacity :: [Occupancy] -> Bool", "withinCapacity = all (\\(n, l, k) -> k <= capacity (n, l))", "",
         "-- | Cited ground states (NIST ASD), expanded to full occupancies.",
         "observed :: [(Int, [Occupancy])]", "observed ="]
    L += [("  [ " if i == 0 else "  , ") + f"({z}, [{triples(occ, '({n}, {l}, {k})')}])" for i, (z, _, occ) in enumerate(atoms)]
    L += ["  ]", "",
          "-- | Each statement the proof languages prove, as a checked value.",
          "checks :: [(String, Bool)]", "checks =",
          "  [ (\"states are the pairs with j < 2l + 1\", all (\\l -> sort (states l) == [(j, s) | j <- [0 .. 2 * l], s <- [False, True]]) [0 .. 20])",
          "  , (\"states without repetition\", all (\\l -> nub (states l) == states l) [0 .. 20])",
          "  , (\"capacity is the number of states\", and [capacity (n, l) == length (states l) | n <- [1 .. 8], l <- [0 .. 20]])",
          "  , (\"shell n holds 2n^2\", all (\\n -> shellCapacity n == 2 * n * n) [0 .. 40])",
          "  , (\"madelung order sorted\", and (zipWith (\\a b -> madelungRank a < madelungRank b) madelungOrder (drop 1 madelungOrder)))",
          f"  , (\"madelung electrons\", all (\\z -> electrons (madelung z) == z) [0 .. {ZMAX}])",
          f"  , (\"madelung within capacity\", all (withinCapacity . madelung) [0 .. {ZMAX}])",
          "  , (\"observed electrons\", all (\\(z, c) -> electrons c == z) observed)",
          "  , (\"observed within capacity\", all (withinCapacity . snd) observed)",
          "  , (\"observed atomic numbers\", map fst observed == [1 .. " + str(len(atoms)) + "])",
          "  , (\"madelung exceptions\", [z | (z, c) <- observed, c /= madelung z] == [" + ", ".join(map(str, exceptions)) + "])",
          "  ]", ""]
    return "\n".join(L)


def outputs() -> dict[str, str]:
    doc, atoms, exceptions = load()
    return {"Lean/Chem/GroundStates.lean": lean(doc, atoms, exceptions),
            "Coq/Chem/GroundStates.v": coq(doc, atoms, exceptions),
            "Agda/Chem/GroundStates.agda": agda(doc, atoms, exceptions),
            "Haskell/src/UMST/Chem/GroundStates.hs": haskell(doc, atoms, exceptions)}


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for rel, text in outputs().items():
        path = os.path.join(ROOT, rel)
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old != text:
            stale.append(rel)
            if not check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                open(path, "w", encoding="utf-8").write(text)
    if check and stale:
        print("FAIL: ground-state modules are stale: " + ", ".join(stale) + " (run scripts/gen_ground_states.py)",
              file=sys.stderr)
        return 1
    print("OK: ground-state modules are current" if check else "wrote: " + ", ".join(stale or ["nothing changed"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
