#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
# SPDX-License-Identifier: MIT
"""Generate the README's census and four-language parity blocks from the sources (one measurement, no hand counts).

The census block counts declarations in the tracked sources: Lean `theorem`/`lemma` (lean_declaration_stats.py,
roots-only and all files), Coq `Theorem`/`Lemma`/`Corollary`/`Proposition`/`Fact`, Agda top-level typed
definitions, Haskell QuickCheck properties (`prop_`), and the counts of tactic `sorry`, Coq `Admitted` and Lean
`axiom`. The parity block tabulates formal_parity.json by statement family: entries present in Lean, Coq, Agda and
Haskell, and the named absences. `--check` fails when a block is stale (CI). Shared byte-identical by umst-formal and
umst-formal-double-slit.
"""
from __future__ import annotations

import collections
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COQ_DECL = re.compile(r"^\s*(Theorem|Lemma|Corollary|Proposition|Fact)\s+\S", re.M)
AGDA_SIG = re.compile(r"^([^\s:;{}()\-][^\s:;{}()]*)\s+:\s", re.M)
AGDA_KEYWORDS = {"module", "open", "import", "data", "record", "infix", "infixl", "infixr", "postulate", "private",
                 "instance", "field", "constructor", "mutual", "where", "variable", "pattern", "syntax"}
HS_PROP = re.compile(r"^(prop_[A-Za-z0-9_']+)\s+::", re.M)
# Proof holes, with the grammar of scripts/check_lean_sorry.sh (CI): a standalone tactic or term, not a user definition
# named `admit` applied to arguments; comments and nested block comments excluded.
HOLE_LINE = re.compile(r"^[ \t]*(sorry|admit)[ \t]*($|;|<;>|\))")
HOLE_EXACT = re.compile(r"\b(exact|refine|apply|show)\s+(sorry|admit)\b")
HOLE_BY = re.compile(r"\bby\s+(sorry|admit)\b")
LINE_COMMENT = re.compile(r"--.*$")
ADMITTED = re.compile(r"^\s*Admitted\.", re.M)
LEAN_AXIOM = re.compile(r"^\s*axiom\s", re.M)
LANGS = ("lean", "coq", "agda", "haskell")


def tracked(*globs: str) -> list[Path]:
    out = subprocess.run(["git", "ls-files", *globs], cwd=ROOT, capture_output=True, text=True, check=True).stdout
    return [ROOT / p for p in out.split()]


def code_lines(src: str):
    """Lines that start outside a Lean block comment `/- … -/` (nesting), as check_lean_sorry.sh reads them."""
    depth = 0
    for line in src.splitlines():
        if depth == 0:
            yield line
        j = 0
        while j < len(line):
            two = line[j:j + 2]
            if depth == 0 and two == "--":
                break
            if two == "/-":
                depth += 1
                j += 2
                continue
            if two == "-/" and depth > 0:
                depth -= 1
                j += 2
                continue
            j += 1


def holes(src: str) -> int:
    if "sorry_detector_fixture" in src:
        return 0
    n = 0
    for line in code_lines(src):
        code = LINE_COMMENT.sub("", line)
        n += bool(HOLE_LINE.match(code) or HOLE_BY.search(code) or HOLE_EXACT.search(code))
    return n


def text(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")


def census() -> list[str]:
    stats = json.loads(subprocess.run([sys.executable, "scripts/lean_declaration_stats.py", "--json"], cwd=ROOT,
                                      capture_output=True, text=True, check=True).stdout)
    lean = tracked("*.lean")
    lean = [p for p in lean if p.name != "lakefile.lean"]
    coq = tracked("*.v")
    agda = tracked("*.agda")
    hs = tracked("*.hs")
    coq_n = sum(len(COQ_DECL.findall(text(p))) for p in coq)
    agda_n = sum(1 for p in agda for m in AGDA_SIG.finditer(text(p)) if m.group(1) not in AGDA_KEYWORDS)
    hs_n = len({m.group(1) for p in hs for m in HS_PROP.finditer(text(p))})
    sorry_n = sum(holes(text(p)) for p in lean)
    admitted_n = sum(len(ADMITTED.findall(text(p))) for p in coq)
    axiom_n = sum(len(LEAN_AXIOM.findall(text(p))) for p in lean)
    r, a = stats["roots_only"], stats["all_lean_glob"]
    return [
        "| Language | Files | Declarations | Gaps |",
        "|---|---:|---|---|",
        f"| Lean 4 | {len(lean)} ({stats['lake_roots_count']} Lake roots) | {r['theorem']} theorems + {r['lemma']} lemmas "
        f"in the roots; {a['theorem']} + {a['lemma']} over all files | {sorry_n} `sorry` or `admit` holes; {axiom_n} `axiom` |",
        f"| Coq | {len(coq)} | {coq_n} theorems and lemmas | {admitted_n} `Admitted` |",
        f"| Agda (`--safe`) | {len(agda)} | {agda_n} top-level typed definitions | `--safe` admits no postulate |",
        f"| Haskell | {len(hs)} | {hs_n} QuickCheck properties | — |",
        "",
        "_Generated by `scripts/gen_readme_blocks.py` from the tracked sources; CI fails when this block is stale._",
    ]


def parity() -> list[str]:
    manifest = json.loads((ROOT / "formal_parity.json").read_text(encoding="utf-8"))
    fam = collections.OrderedDict()
    for s in manifest["statements"]:
        f = s["id"].split(".")[0]
        row = fam.setdefault(f, {"n": 0, **{l: 0 for l in LANGS}})
        row["n"] += 1
        for l in LANGS:
            if isinstance(s.get(l), dict) and "name" in s[l]:
                row[l] += 1
    lines = ["| Statement family | Statements | Lean | Coq | Agda | Haskell |", "|---|---:|---:|---:|---:|---:|"]
    tot = {"n": 0, **{l: 0 for l in LANGS}}
    for f, row in fam.items():
        lines.append(f"| `{f}` | {row['n']} | " + " | ".join(str(row[l]) for l in LANGS) + " |")
        for k in tot:
            tot[k] += row[k]
    lines.append(f"| **all** | **{tot['n']}** | " + " | ".join(f"**{tot[l]}**" for l in LANGS) + " |")
    absent = 4 * tot["n"] - sum(tot[l] for l in LANGS)
    lines += ["", f"{absent} entries are named absences, each with its reason in `formal_parity.json` "
              f"(bound {manifest['max_absent']}); `scripts/check_formal_parity.py` checks every named declaration exists.",
              "", "_Generated by `scripts/gen_readme_blocks.py` from `formal_parity.json`; CI fails when this block is stale._"]
    return lines


def replace(doc: str, name: str, body: list[str]) -> str | None:
    begin, end = f"<!-- {name}:begin -->", f"<!-- {name}:end -->"
    if begin not in doc or end not in doc:
        return None
    head, rest = doc.split(begin, 1)
    _, tail = rest.split(end, 1)
    return head + begin + "\n" + "\n".join(body) + "\n" + end + tail


def main() -> int:
    check = "--check" in sys.argv
    path = ROOT / "README.md"
    doc = path.read_text(encoding="utf-8")
    new, missing = doc, []
    for name, body in (("census", census()), ("parity", parity())):
        out = replace(new, name, body)
        if out is None:
            missing.append(name)
        else:
            new = out
    if missing:
        print(f"FAIL: README.md has no block for: {', '.join(missing)}", file=sys.stderr)
        return 1
    if new != doc:
        if check:
            print("FAIL: README census or parity block is stale (run scripts/gen_readme_blocks.py)", file=sys.stderr)
            return 1
        path.write_text(new, encoding="utf-8")
        print("wrote README.md census and parity blocks")
    else:
        print("OK: README census and parity blocks are current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
