#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
# SPDX-License-Identifier: MIT
"""Generate the constants modules and README tables from constants/constants.json (one source, four languages).

Byte-identical in umst-formal and umst-formal-double-slit, and so is constants/constants.json
(scripts/check_shared_lean_drift.sh compares both with the sibling). Every value is an exact rational, so each
language checks it by exact computation:

  cited     a defining constant of the SI (or another cited authority): a definition with its authority
  measured  a cited measurement: the value and its standard uncertainty, both exact rationals
  derived   a definition by its formula, and two theorems: `<id>_value` (the formula equals the exact value) and
            `<id>_derivation` (the value times the formula's denominator equals its numerator, the statement every
            language proves the same way; Agda proves it on unnormalised rationals by `refl`). A formula is a
            monomial (a product and quotient of constants and integers) or linear (a sum and difference of
            constants and integers); a linear formula's `_value` is its derivation, and Agda states it as
            `<id> ≃ <formula>` by `refl`
  crosscheck  for a derived row with a published value: |derived − published| ≤ published uncertainty, or, with
            "bound": "propagated", ≤ the uncertainty its measured inputs carry to first order (Σ |exponent| · u/x of
            each measured factor, times the derived value): for a published value itself adjusted from other data
            (CODATA's m_e from R∞), whose own uncertainty is smaller than its inputs' rounding
  policy    a documented model or configuration choice, never counted as a constant: its value, its reason, and the
            range it must lie in, given by two rows of the table; `<id>_in_range` proves low ≤ value ≤ high

Lean (umst-formal only; umst-formal-double-slit imports it through Lake), Coq, Agda and Haskell modules are written
where the repository keeps that language. `--check` regenerates in memory and fails on any difference.
"""
from __future__ import annotations

import json
import os
import re
import sys
from fractions import Fraction

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
REPO = os.path.basename(ROOT)
HOME = "umst-formal"  # the Lean module lives here; the sibling imports it
FIBRE = {"umst-formal": "acting", "umst-formal-double-slit": "knowing"}.get(REPO, "acting")
SPDX = "SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar"
HEADER = "Generated by scripts/gen_constants.py from constants/constants.json; edit the table, not this file."


def big(text: str) -> int:
    """`602214076*10^15`, `10^42` or a plain integer."""
    value = 1
    for factor in text.split("*"):
        base, _, exp = factor.strip().partition("^")
        value *= int(base) ** (int(exp) if exp else 1)
    return value


def tokens(formula: str) -> list[str]:
    return re.findall(r"[A-Za-z_]\w*|\d+|[()*/]", formula)


def factors(formula: str) -> list[tuple[str, int]]:
    """A product of factors with exponents ±1 (the formulas are monomials)."""
    toks = tokens(formula)
    pos = 0

    def expr(sign: int) -> list[tuple[str, int]]:
        nonlocal pos
        out = term(sign)
        while pos < len(toks) and toks[pos] in "*/":
            op = toks[pos]
            pos += 1
            out += term(sign if op == "*" else -sign)
        return out

    def term(sign: int) -> list[tuple[str, int]]:
        nonlocal pos
        tok = toks[pos]
        pos += 1
        if tok == "(":
            inner = expr(sign)
            pos += 1  # ')'
            return inner
        return [(tok, sign)]

    return expr(1)


def linear(formula: str) -> bool:
    """A sum or difference of constants and integers (no product or quotient)."""
    return bool(re.search(r"[+-]", formula))


def terms(formula: str) -> list[tuple[str, int]]:
    """The signed terms of a linear formula."""
    out, sign = [], 1
    for tok in re.findall(r"[A-Za-z_]\w*|\d+|[+-]", formula):
        if tok in "+-":
            sign = 1 if tok == "+" else -1
        else:
            out.append((tok, sign))
            sign = 1
    return out


def load() -> dict:
    with open(os.path.join(ROOT, "constants/constants.json"), encoding="utf-8") as f:
        return json.load(f)


def values(table: dict) -> dict[str, Fraction]:
    out: dict[str, Fraction] = {}
    for c in table["constants"]:
        if c["status"] in ("cited", "measured", "policy"):
            out[c["id"]] = Fraction(big(c["num"]), big(c["den"]))
    for c in table["constants"]:
        if c["status"] == "derived":
            value = lambda name: Fraction(int(name)) if name.isdigit() else out[name]
            if linear(c["formula"]):
                v = sum((sign * value(name) for name, sign in terms(c["formula"])), Fraction(0))
            else:
                v = Fraction(1)
                for name, sign in factors(c["formula"]):
                    v = v * value(name) if sign > 0 else v / value(name)
            out[c["id"]] = v
    return out


def split(c: dict) -> tuple[list[str], list[str]]:
    if linear(c["formula"]):
        return [], []  # a linear formula has no denominator; its `_value` is its derivation
    fs = factors(c["formula"])
    return [n for n, s in fs if s > 0], [n for n, s in fs if s < 0]


def frac(c: dict, prefix: str) -> Fraction:
    return Fraction(big(c[prefix + "num"]), big(c[prefix + "den"]))


def crossbound(c: dict, table: dict, vals: dict[str, Fraction]) -> tuple[Fraction, Fraction]:
    """The published value of a derived row's cross-check and the bound its distance must meet."""
    x = c["crosscheck"]
    if x.get("bound") != "propagated":
        return frac(x, ""), frac(x, "uncertainty_")
    rows = {r["id"]: r for r in table["constants"]}
    rel = sum((frac(rows[n], "uncertainty_") / vals[n] for n, _ in factors(c["formula"])
               if n in rows and rows[n]["status"] == "measured"), Fraction(0))
    return frac(x, ""), abs(vals[c["id"]]) * rel


def crosswhat(c: dict) -> str:
    x = c["crosscheck"]
    return (f"the uncertainty its measured inputs carry (first order), from the {x['authority']} value"
            if x.get("bound") == "propagated" else f"the {x['authority']} value's standard uncertainty")


# ------------------------------------------------------------------------------------------------- Lean (ℚ)

def lean_q(v: Fraction) -> str:
    return f"({v.numerator} : ℚ)" if v.denominator == 1 else f"({v.numerator} : ℚ) / {v.denominator}"


def lean(table: dict, vals: dict[str, Fraction]) -> str:
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", "/-", f"  {HEADER}", "",
         "  The constants of the UMST ecosystem as exact rationals: the seven defining constants of the SI (cited),",
         "  cited measurements with their standard uncertainty, and constants derived from them, each with its exact",
         "  value and its defining equation proved by computation. `Constants.SIBridge` identifies these values with",
         "  the real-valued constants of the Landauer chain and states the laws that carry the second law.", "-/", "",
         "import Mathlib.Tactic.NormNum", "import Mathlib.Algebra.Order.Group.Abs", "", "namespace UMST.Constants.SI", ""]
    ids = [c["id"] for c in table["constants"]]
    for c in table["constants"]:
        doc = f"/-- {c['symbol']}: {c['name']} [{c['unit']}]"
        if c["status"] == "cited":
            L += [doc + f"; cited: {table['authorities'][c['authority']].split(':')[0]}. -/",
                  f"def {c['id']} : ℚ := {lean_q(frac(c, ''))}", ""]
        elif c["status"] == "measured":
            L += [doc + f"; measured, cited from {c['authority']}. -/", f"def {c['id']} : ℚ := {lean_q(frac(c, ''))}",
                  f"/-- Standard uncertainty of {c['symbol']} ({c['authority']}). -/",
                  f"def {c['id']}Uncertainty : ℚ := {lean_q(frac(c, 'uncertainty_'))}", ""]
        elif c["status"] == "policy":
            lo, hi = c["range"]["low"], c["range"]["high"]
            L += [doc + f"; policy (a model choice, not a constant): {c['reason']}. -/",
                  f"def {c['id']} : ℚ := {lean_q(frac(c, ''))}", "",
                  f"/-- The choice lies in its range [{lo}, {hi}]. -/",
                  f"theorem {c['id']}_in_range : {lo} ≤ {c['id']} ∧ {c['id']} ≤ {hi} := by",
                  f"  norm_num [{c['id']}, {lo}, {hi}]", ""]
        else:
            num, den = split(c)
            deps, todo = [], [c["id"]]  # every constant the formula reaches, so norm_num evaluates it
            formulas = {r["id"]: r.get("formula", "") for r in table["constants"]}
            while todo:
                for x in re.findall(r"[A-Za-z_]\w*", formulas.get(todo.pop(), "")):
                    if x in formulas and x not in deps:
                        deps.append(x)
                        todo.append(x)
            unfold = ", ".join(x for x in ids if x in deps) or c["id"]
            prod = lambda xs: " * ".join(xs) if xs else "1"
            L += [doc + f"; derived: {c['formula']}. -/", f"def {c['id']} : ℚ := {c['formula']}", "",
                  f"theorem {c['id']}_value : {c['id']} = {lean_q(vals[c['id']])} := by",
                  f"  norm_num [{c['id']}, {unfold}]", "",
                  ]
            if den:  # with a denominator the multiplicative form is a second statement; without one, `_value` is it
                L += [f"theorem {c['id']}_derivation : {lean_q(vals[c['id']])} * ({prod(den)}) = {prod(num)} := by",
                      f"  norm_num [{unfold}]", ""]
            if "crosscheck" in c:
                x = c["crosscheck"]
                pub, u = crossbound(c, table, vals)
                L += [f"/-- {c['symbol']} derived here lies within {crosswhat(c)}. -/",
                      f"theorem {c['id']}_within_{x['authority']} :",
                      f"    |{c['id']} - {lean_q(pub)}| ≤ {lean_q(u)} := by",
                      f"  rw [{c['id']}_value, abs_le]", "  constructor <;> norm_num", ""]
    L += ["end UMST.Constants.SI", ""]
    return "\n".join(L)


# ------------------------------------------------------------------------------------------------- Coq (Q)

def coq_q(v: Fraction) -> str:
    return f"(Qmake {v.numerator} {v.denominator})"


def coq(table: dict, vals: dict[str, Fraction]) -> str:
    L = [f"(* {SPDX} *)", "(* SPDX-License-Identifier: MIT *)", f"(* {HEADER} *)",
         "(* Exact rational constants; each derived constant's value and defining equation are proved by        *)",
         "(* computation (twin of Lean/Constants/SI.lean). Zero Axiom, Parameter or Admitted.                  *)", "",
         "From Stdlib Require Import QArith.", "Open Scope Q_scope.", ""]
    for c in table["constants"]:
        if c["status"] in ("cited", "measured"):
            L.append(f"(* {c['symbol']}: {c['name']} [{c['unit']}], {c['status']} ({c['authority']}) *)")
            L.append(f"Definition {c['id']} : Q := {coq_q(frac(c, ''))}.")
            if c["status"] == "measured":
                L.append(f"Definition {c['id']}Uncertainty : Q := {coq_q(frac(c, 'uncertainty_'))}.")
            L.append("")
        elif c["status"] == "policy":
            lo, hi = c["range"]["low"], c["range"]["high"]
            L += [f"(* {c['symbol']}: {c['name']} [{c['unit']}], policy (a model choice, not a constant): {c['reason']} *)",
                  f"Definition {c['id']} : Q := {coq_q(frac(c, ''))}.",
                  f"Lemma {c['id']}_in_range : {lo} <= {c['id']} /\\ {c['id']} <= {hi}.",
                  "Proof. split; vm_compute; discriminate. Qed.", ""]
        else:
            num, den = split(c)
            prod = lambda xs: " * ".join(xs) if xs else "1"
            L += [f"(* {c['symbol']}: {c['name']} [{c['unit']}], derived: {c['formula']} *)",
                  f"Definition {c['id']} : Q := {c['formula']}.",
                  f"Lemma {c['id']}_value : {c['id']} == {coq_q(vals[c['id']])}.",
                  "Proof. vm_compute. reflexivity. Qed.",
                  ]
            if den:
                L += [f"Lemma {c['id']}_derivation : {coq_q(vals[c['id']])} * ({prod(den)}) == {prod(num)}.",
                      "Proof. vm_compute. reflexivity. Qed."]
            if "crosscheck" in c:
                x = c["crosscheck"]
                pub, u = crossbound(c, table, vals)
                L += [f"Lemma {c['id']}_within_{x['authority']} :",
                      f"  {coq_q(pub - u)} <= {c['id']} /\\ {c['id']} <= {coq_q(pub + u)}.",
                      "Proof. split; vm_compute; discriminate. Qed."]
            L.append("")
    return "\n".join(L)


# ------------------------------------------------------------------------------------------------- Agda (ℚᵘ)

def agda_q(v: Fraction) -> str:
    sign = "-[1+ " + str(-v.numerator - 1) + " ]" if v.numerator < 0 else f"+ {v.numerator}"
    return f"(mkℚᵘ ({sign}) {v.denominator - 1})"


def agda(table: dict, vals: dict[str, Fraction]) -> str:
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", f"-- {HEADER}",
         "-- Exact constants on unnormalised rationals: each derived constant's defining equation holds by `refl`",
         "-- (cross-multiplication of integers, no normalisation). Twin of Lean/Constants/SI.lean.", "",
         "{-# OPTIONS --without-K --safe #-}", "", "module Constants.SI where", "",
         "open import Data.Integer using (+_; -[1+_])",
         "open import Data.Rational.Unnormalised.Base using (ℚᵘ; mkℚᵘ; _*_; _+_; _-_; _≃_; *≡*; _≤_; *≤*)",
         "open import Data.Product using (_×_; _,_)",
         "open import Relation.Binary.PropositionalEquality using (refl)",
         "open import Relation.Nullary.Decidable using (toWitness)",
         "import Data.Integer.Properties as ℤ", "",
         "private", "  two : ℚᵘ", "  two = mkℚᵘ (+ 2) 0", ""]
    for c in table["constants"]:
        if c["status"] in ("cited", "measured"):
            L += [f"-- {c['symbol']}: {c['name']} [{c['unit']}], {c['status']} ({c['authority']})",
                  f"{c['id']} : ℚᵘ", f"{c['id']} = {agda_q(frac(c, ''))}"]
            if c["status"] == "measured":
                L += [f"{c['id']}Uncertainty : ℚᵘ", f"{c['id']}Uncertainty = {agda_q(frac(c, 'uncertainty_'))}"]
            L.append("")
        elif c["status"] == "policy":
            lo, hi = c["range"]["low"], c["range"]["high"]
            L += [f"-- {c['symbol']}: {c['name']} [{c['unit']}], policy (a model choice, not a constant): {c['reason']}",
                  f"{c['id']} : ℚᵘ", f"{c['id']} = {agda_q(frac(c, ''))}", "",
                  f"{c['id']}-in-range : ({lo} ≤ {c['id']}) × ({c['id']} ≤ {hi})",
                  f"{c['id']}-in-range = *≤* (toWitness {{a? = _ ℤ.≤? _}} _) , *≤* (toWitness {{a? = _ ℤ.≤? _}} _)", ""]
        else:
            num, den = split(c)
            term = lambda xs: " * ".join("two" if x == "2" else x for x in xs) if xs else "mkℚᵘ (+ 1) 0"
            if linear(c["formula"]):
                lit = lambda n: agda_q(Fraction(int(n))) if n.isdigit() else n
                rhs = re.sub(r"[A-Za-z_]\w*|\d+", lambda m: lit(m.group(0)), c["formula"])
                statement = f"{c['id']} ≃ {rhs}"
            else:
                statement = f"{c['id'] + (' * (' + term(den) + ')' if den else '')} ≃ {term(num)}"
            L += [f"-- {c['symbol']}: {c['name']} [{c['unit']}], derived: {c['formula']}",
                  f"{c['id']} : ℚᵘ", f"{c['id']} = {agda_q(vals[c['id']])}", "",
                  f"{c['id']}-derivation : {statement}",
                  f"{c['id']}-derivation = *≡* refl", ""]
            if "crosscheck" in c:
                x = c["crosscheck"]
                pub, u = crossbound(c, table, vals)
                L += [f"{c['id']}-within-{x['authority']} : ({agda_q(pub - u)} ≤ {c['id']}) × ({c['id']} ≤ {agda_q(pub + u)})",
                      f"{c['id']}-within-{x['authority']} = *≤* (toWitness {{a? = _ ℤ.≤? _}} _) , *≤* (toWitness {{a? = _ ℤ.≤? _}} _)", ""]
    return "\n".join(L)


# ------------------------------------------------------------------------------------------------- Haskell (Rational)

def haskell(table: dict, vals: dict[str, Fraction]) -> str:
    L = [f"-- {SPDX}", "-- SPDX-License-Identifier: MIT", f"-- {HEADER}", "-- |",
         "-- Exact constants as 'Rational' (twin of Lean/Constants/SI.lean): the runtime reads these values and",
         "-- 'derivations' lists every derived constant's defining equation, checked by the test suite.",
         "module UMST.Constants.SI where", "", "import Data.Ratio ((%))", ""]
    for c in table["constants"]:
        if c["status"] in ("cited", "measured"):
            v = frac(c, "")
            L += [f"-- | {c['symbol']}: {c['name']} [{c['unit']}], {c['status']} ({c['authority']}).",
                  f"{c['id']} :: Rational", f"{c['id']} = {v.numerator} % {v.denominator}"]
            if c["status"] == "measured":
                u = frac(c, "uncertainty_")
                L += [f"{c['id']}Uncertainty :: Rational", f"{c['id']}Uncertainty = {u.numerator} % {u.denominator}"]
            L.append("")
        elif c["status"] == "policy":
            v = frac(c, "")
            L += [f"-- | {c['symbol']}: {c['name']} [{c['unit']}], policy (a model choice, not a constant): {c['reason']}.",
                  f"{c['id']} :: Rational", f"{c['id']} = {v.numerator} % {v.denominator}", ""]
        else:
            v = vals[c["id"]]
            L += [f"-- | {c['symbol']}: {c['name']} [{c['unit']}], derived: {c['formula']}.",
                  f"{c['id']} :: Rational", f"{c['id']} = {c['formula']}", ""]
    L += ["-- | Each derived constant against its exact value, and each cross-check against its published value.",
          "derivations :: [(String, Bool)]", "derivations ="]
    rows = []
    for c in table["constants"]:
        if c["status"] == "derived":
            v = vals[c["id"]]
            rows.append(f'("{c["id"]}", {c["id"]} == {v.numerator} % {v.denominator})')
            if "crosscheck" in c:
                x = c["crosscheck"]
                pub, u = crossbound(c, table, vals)
                rows.append(f'("{c["id"]} within {x["authority"]}", abs ({c["id"]} - {pub.numerator} % {pub.denominator}) <= {u.numerator} % {u.denominator})')
        if c["status"] == "policy":
            rows.append(f'("{c["id"]} in its range", {c["range"]["low"]} <= {c["id"]} && {c["id"]} <= {c["range"]["high"]})')
    L += ["  [ " + "\n  , ".join(rows), "  ]", ""]
    return "\n".join(L)


# ------------------------------------------------------------------------------------------------- README table

SUP = str.maketrans("-0123456789", "⁻⁰¹²³⁴⁵⁶⁷⁸⁹")


def terminating(v: Fraction) -> bool:
    d = v.denominator
    for p in (2, 5):
        while d % p == 0:
            d //= p
    return d == 1


def scientific(v: Fraction, digits: int | None = None) -> str:
    """`m × 10ⁿ` with every significant digit of a terminating value, or `digits` digits otherwise."""
    if v == 0:
        return "0"
    sign = "-" if v < 0 else ""
    v = abs(v)
    exp = len(str(v.numerator)) - len(str(v.denominator))
    if v < Fraction(10) ** exp:
        exp -= 1
    m = v / Fraction(10) ** exp
    if digits is None:
        text = ""
        while m != 0 and len(text) < 40:
            d = m.numerator // m.denominator
            text += str(d)
            m = (m - d) * 10
    else:
        q = round(m * 10 ** (digits - 1))
        if q >= 10 ** digits:
            q //= 10
            exp += 1
        text = str(q).rstrip("0") or "0"
    mant = text[0] + ("." + text[1:] if len(text) > 1 else "")
    return f"{sign}{mant}" if exp == 0 else f"{sign}{mant} × 10{str(exp).translate(SUP)}"


def shown(v: Fraction) -> str:
    return scientific(v) if terminating(v) else "≈ " + scientific(v, 12)


def readme(table: dict, vals: dict[str, Fraction]) -> str:
    rows = ["| Symbol | Constant | Kind | Value | Unit | Derivation or authority | Proved by |",
            "|---|---|---|---|---|---|---|"]
    used, links = set(), []
    for c in table["constants"]:
        if c["fibre"] not in ("both", FIBRE):
            continue
        v = vals[c["id"]]
        if c["status"] == "measured":
            value = f"{scientific(v)} ± {scientific(frac(c, 'uncertainty_'))}"
        else:
            value = shown(v) + (" (exact)" if terminating(v) else "")
        if c["status"] == "derived":
            how = f"`{c['formula']}`"
            proof = f"`{c['id']}_value`" + (f", `{c['id']}_derivation`" if split(c)[1] else "") + (
                f", `{c['id']}_within_{c['crosscheck']['authority']}`" if "crosscheck" in c else "")
            if "crosscheck" in c:
                used.add(c["crosscheck"]["authority"])
        elif c["status"] == "policy":
            how = f"model choice: {c['reason']}; range [{c['range']['low']}, {c['range']['high']}]"
            proof = f"`{c['id']}_in_range`"
        else:
            how = c["authority"]
            used.add(c["authority"])
            proof = "a definition (cited)" if c["status"] == "cited" else "a definition with its uncertainty (cited)"
        rows.append(f"| {c['symbol']} | {c['name']} | {c['status']} | {value} | {c['unit']} | {how} | {proof} |")
        if c.get("second_law"):
            links.append(f"- {c['symbol']}: {c['second_law']}.")
    out = rows + [""] + [f"- {a}: {table['authorities'][a]}." for a in sorted(used)]
    if links:
        out += ["", "Where these constants enter the second law:", ""] + links
    if any(r.split(" | ")[3].startswith("≈") for r in rows[2:]):
        out += ["", "Values marked ≈ are shown to twelve significant digits; the modules hold them as exact rationals."]
    return "\n".join(out)


def outputs() -> dict[str, str]:
    table = load()
    vals = values(table)
    out = {}
    if REPO == HOME:
        out["Lean/Constants/SI.lean"] = lean(table, vals)
    out["Coq/Constants/SI.v"] = coq(table, vals)
    out["Agda/Constants/SI.agda"] = agda(table, vals)
    hs = "Haskell/UMST/Constants/SI.hs" if REPO == HOME else "Haskell/src/UMST/Constants/SI.hs"
    out[hs] = haskell(table, vals)
    return out


def replace_block(text: str, body: str) -> str:
    return re.sub(r"(<!-- constants:begin -->\n).*?(<!-- constants:end -->)", lambda m: m.group(1) + body + "\n" + m.group(2),
                  text, flags=re.S)


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    files = outputs()
    for rel, text in files.items():
        path = os.path.join(ROOT, rel)
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old != text:
            stale.append(rel)
            if not check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "w", encoding="utf-8") as f:
                    f.write(text)
    table = load()
    block = readme(table, values(table))
    rpath = os.path.join(ROOT, "README.md")
    rtext = open(rpath, encoding="utf-8").read()
    if "<!-- constants:begin -->" in rtext:
        new = replace_block(rtext, block)
        if new != rtext:
            stale.append("README.md")
            if not check:
                open(rpath, "w", encoding="utf-8").write(new)
    elif check:
        stale.append("README.md (no constants block)")
    if check and stale:
        print("FAIL: generated constants are stale: " + ", ".join(stale) + " (run scripts/gen_constants.py)",
              file=sys.stderr)
        return 1
    print(("OK: constants are current" if check else "wrote: " + ", ".join(stale or ["nothing changed"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
