-- SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
-- SPDX-License-Identifier: MIT
-- Generated by scripts/gen_constants.py from constants/constants.json; edit the table, not this file.
-- |
-- Exact constants as 'Rational' (twin of Lean/Constants/SI.lean): the runtime reads these values and
-- 'derivations' lists every derived constant's defining equation, checked by the test suite.
module UMST.Constants.SI where

import Data.Ratio ((%))

-- | ΔνCs: caesium-133 hyperfine transition frequency [Hz], cited (SI2019).
caesiumHyperfineFrequency :: Rational
caesiumHyperfineFrequency = 9192631770 % 1

-- | c: speed of light in vacuum [m s⁻¹], cited (SI2019).
speedOfLight :: Rational
speedOfLight = 299792458 % 1

-- | h: Planck constant [J s], cited (SI2019).
planck :: Rational
planck = 132521403 % 200000000000000000000000000000000000000000

-- | e: elementary charge [C], cited (SI2019).
elementaryCharge :: Rational
elementaryCharge = 801088317 % 5000000000000000000000000000

-- | k_B: Boltzmann constant [J K⁻¹], cited (SI2019).
boltzmann :: Rational
boltzmann = 1380649 % 100000000000000000000000000000

-- | N_A: Avogadro constant [mol⁻¹], cited (SI2019).
avogadro :: Rational
avogadro = 602214076000000000000000 % 1

-- | K_cd: luminous efficacy of 540 THz radiation [lm W⁻¹], cited (SI2019).
luminousEfficacy :: Rational
luminousEfficacy = 683 % 1

-- | R: molar gas constant [J mol⁻¹ K⁻¹], derived: avogadro * boltzmann.
gasConstant :: Rational
gasConstant = avogadro * boltzmann

-- | F: Faraday constant [C mol⁻¹], derived: avogadro * elementaryCharge.
faraday :: Rational
faraday = avogadro * elementaryCharge

-- | c²: mass–energy conversion factor [m² s⁻²], derived: speedOfLight * speedOfLight.
speedOfLightSquared :: Rational
speedOfLightSquared = speedOfLight * speedOfLight

-- | K_J: Josephson constant [Hz V⁻¹], derived: 2 * elementaryCharge / planck.
josephson :: Rational
josephson = 2 * elementaryCharge / planck

-- | R_K: von Klitzing constant [Ω], derived: planck / (elementaryCharge * elementaryCharge).
vonKlitzing :: Rational
vonKlitzing = planck / (elementaryCharge * elementaryCharge)

-- | Φ₀: magnetic flux quantum [Wb], derived: planck / (2 * elementaryCharge).
fluxQuantum :: Rational
fluxQuantum = planck / (2 * elementaryCharge)

-- | G₀: conductance quantum [S], derived: 2 * elementaryCharge * elementaryCharge / planck.
conductanceQuantum :: Rational
conductanceQuantum = 2 * elementaryCharge * elementaryCharge / planck

-- | α: fine-structure constant [1], measured (CODATA2022).
fineStructure :: Rational
fineStructure = 72973525643 % 10000000000000
fineStructureUncertainty :: Rational
fineStructureUncertainty = 11 % 10000000000000

-- | m_e: electron mass [kg], measured (CODATA2022).
electronMass :: Rational
electronMass = 91093837139 % 100000000000000000000000000000000000000000
electronMassUncertainty :: Rational
electronMassUncertainty = 7 % 25000000000000000000000000000000000000000

-- | R∞: Rydberg constant [m^-1], derived: fineStructure * fineStructure * electronMass * speedOfLight / (2 * planck).
rydberg :: Rational
rydberg = fineStructure * fineStructure * electronMass * speedOfLight / (2 * planck)

-- | E_h: Hartree energy [J], derived: fineStructure * fineStructure * electronMass * speedOfLight * speedOfLight.
hartreeEnergy :: Rational
hartreeEnergy = fineStructure * fineStructure * electronMass * speedOfLight * speedOfLight

-- | λ_C: Compton wavelength [m], derived: planck / (electronMass * speedOfLight).
comptonWavelength :: Rational
comptonWavelength = planck / (electronMass * speedOfLight)

-- | ε₀: vacuum electric permittivity [F m⁻¹], derived: elementaryCharge * elementaryCharge / (2 * fineStructure * planck * speedOfLight).
vacuumPermittivity :: Rational
vacuumPermittivity = elementaryCharge * elementaryCharge / (2 * fineStructure * planck * speedOfLight)

-- | μ₀: vacuum magnetic permeability [N A⁻²], derived: 2 * fineStructure * planck / (elementaryCharge * elementaryCharge * speedOfLight).
vacuumPermeability :: Rational
vacuumPermeability = 2 * fineStructure * planck / (elementaryCharge * elementaryCharge * speedOfLight)

-- | w_n: non-evaporable water at complete hydration (Powers' model) [kg per kg cement], cited (Bentz2009).
nonEvaporableWater :: Rational
nonEvaporableWater = 23 % 100

-- | w_cs: chemical shrinkage at complete hydration (Powers' model) [kg water per kg cement], cited (Bentz2009).
chemicalShrinkage :: Rational
chemicalShrinkage = 8 % 125

-- | w_g: gel water at complete hydration (Powers' model) [kg per kg cement], cited (Bentz2009).
gelWater :: Rational
gelWater = 19 % 100

-- | ρ_w: density of water assigned in Powers' model [kg m⁻³], cited (Bentz2009).
waterDensity :: Rational
waterDensity = 1000 % 1

-- | ρ_c: density of cement assigned in Powers' model [kg m⁻³], cited (Bentz2009).
cementDensity :: Rational
cementDensity = 3150 % 1

-- | (w/c)*: water-cement ratio at which sealed paste just hydrates completely [1], derived: nonEvaporableWater + gelWater.
criticalWcSealed :: Rational
criticalWcSealed = nonEvaporableWater + gelWater

-- | (w/c)_s: water-cement ratio below which space limits complete hydration [1], derived: nonEvaporableWater + gelWater - chemicalShrinkage.
criticalWcSpace :: Rational
criticalWcSpace = nonEvaporableWater + gelWater - chemicalShrinkage

-- | ρ_c/ρ_w: specific gravity of cement in Powers' model [1], derived: cementDensity / waterDensity.
densityRatio :: Rational
densityRatio = cementDensity / waterDensity

-- | v_cs: chemical-shrinkage volume per volume of cement reacted [1], derived: chemicalShrinkage * densityRatio.
shrinkageVolume :: Rational
shrinkageVolume = chemicalShrinkage * densityRatio

-- | v_gw: gel-water volume per volume of cement reacted [1], derived: gelWater * densityRatio.
gelWaterVolume :: Rational
gelWaterVolume = gelWater * densityRatio

-- | v_cw: capillary water consumed per volume of cement reacted [1], derived: criticalWcSealed * densityRatio.
capillaryConsumption :: Rational
capillaryConsumption = criticalWcSealed * densityRatio

-- | w_n − w_cs: water bound into gel solids per mass of cement reacted [kg per kg cement], derived: nonEvaporableWater - chemicalShrinkage.
boundWater :: Rational
boundWater = nonEvaporableWater - chemicalShrinkage

-- | v_b: volume of water bound into gel solids per volume of cement reacted [1], derived: boundWater * densityRatio.
boundWaterVolume :: Rational
boundWaterVolume = boundWater * densityRatio

-- | v_gs: gel-solids volume per volume of cement reacted [1], derived: 1 + boundWaterVolume.
gelSolidsVolume :: Rational
gelSolidsVolume = 1 + boundWaterVolume

-- | A: intrinsic strength of the gel in Powers' gel-space law [MPa], cited (Powers1958).
powersGelStrength :: Rational
powersGelStrength = 234 % 1

-- | n: exponent of Powers' gel-space law [1], cited (Powers1958).
powersGelExponent :: Rational
powersGelExponent = 3 % 1

-- | Q_C3S: heat released by complete hydration of tricalcium silicate (alite) [J/g], measured (Taylor1997).
hydrationHeatC3S :: Rational
hydrationHeatC3S = 517 % 1
hydrationHeatC3SUncertainty :: Rational
hydrationHeatC3SUncertainty = 13 % 1

-- | Q_C2S: heat released by complete hydration of dicalcium silicate (belite) [J/g], cited (Taylor1997).
hydrationHeatC2S :: Rational
hydrationHeatC2S = 262 % 1

-- | Q_C3A,AFm: heat released by complete hydration of tricalcium aluminate to AFm [J/g], cited (Taylor1997).
hydrationHeatC3AtoAFm :: Rational
hydrationHeatC3AtoAFm = 1144 % 1

-- | Q_C3A,AFt: heat released by complete hydration of tricalcium aluminate to AFt [J/g], cited (Taylor1997).
hydrationHeatC3AtoAFt :: Rational
hydrationHeatC3AtoAFt = 1672 % 1

-- | Q_C4AF: heat released by complete hydration of tetracalcium aluminoferrite [J/g], cited (Taylor1997).
hydrationHeatC4AF :: Rational
hydrationHeatC4AF = 418 % 1

-- | Q_hyd: heat of complete hydration of a portland cement (model default) [J/g], policy (a model choice, not a constant): a cement's heat of complete hydration is the mass-weighted sum of its phases' heats, so for a clinker of the four phases it lies between the least and the greatest phase heat; 450 is the gate's default for an unspecified portland cement.
hydrationHeatDefault :: Rational
hydrationHeatDefault = 450 % 1

-- | Each derived constant against its exact value, and each cross-check against its published value.
derivations :: [(String, Bool)]
derivations =
  [ ("gasConstant", gasConstant == 207861565453831 % 25000000000000)
  , ("faraday", faraday == 120606665154137523 % 1250000000000)
  , ("speedOfLightSquared", speedOfLightSquared == 89875517873681764 % 1)
  , ("josephson", josephson == 21362355120000000000000 % 44173801)
  , ("vonKlitzing", vonKlitzing == 5521725125000000000000 % 213914163877964163)
  , ("fluxQuantum", fluxQuantum == 44173801 % 21362355120000000000000)
  , ("conductanceQuantum", conductanceQuantum == 213914163877964163 % 2760862562500000000000)
  , ("rydberg", rydberg == 10387530739584650529984309579749063654017 % 946581450000000000000000000000000)
  , ("rydberg within CODATA2022", abs (rydberg - 10973731568157 % 1000000) <= 3162247663446000961408641811451 % 473290725000000000000000000000000)
  , ("hartreeEnergy", hartreeEnergy == 10899361805397240985092496046210715856126763013251 % 2500000000000000000000000000000000000000000000000000000000000000000)
  , ("hartreeEnergy within CODATA2022", abs (hartreeEnergy - 2179872361103 % 500000000000000000000000000000) <= 3318062999402316824718709548837637427953 % 1250000000000000000000000000000000000000000000000000000000000000000)
  , ("comptonWavelength", comptonWavelength == 18931629 % 7802641527014999332)
  , ("comptonWavelength within CODATA2022", abs (comptonWavelength - 121315511769 % 50000000000000000000000) <= 19 % 25000000000000000000000)
  , ("vacuumPermittivity", vacuumPermittivity == 213914163877964163 % 24159659615848077226571442350)
  , ("vacuumPermittivity within CODATA2022", abs (vacuumPermittivity - 22135469547 % 2500000000000000000000) <= 7 % 5000000000000000000000)
  , ("vacuumPermeability", vacuumPermeability == 11512564285793853725 % 9161407569998526923097522)
  , ("vacuumPermeability within CODATA2022", abs (vacuumPermeability - 125663706127 % 100000000000000000) <= 1 % 5000000000000000)
  , ("criticalWcSealed", criticalWcSealed == 21 % 50)
  , ("criticalWcSpace", criticalWcSpace == 89 % 250)
  , ("densityRatio", densityRatio == 63 % 20)
  , ("shrinkageVolume", shrinkageVolume == 126 % 625)
  , ("gelWaterVolume", gelWaterVolume == 1197 % 2000)
  , ("capillaryConsumption", capillaryConsumption == 1323 % 1000)
  , ("boundWater", boundWater == 83 % 500)
  , ("boundWaterVolume", boundWaterVolume == 5229 % 10000)
  , ("gelSolidsVolume", gelSolidsVolume == 15229 % 10000)
  , ("hydrationHeatDefault in its range", hydrationHeatC2S <= hydrationHeatDefault && hydrationHeatDefault <= hydrationHeatC3AtoAFt)
  ]
