-- SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
-- SPDX-License-Identifier: MIT

/-
-/

import Lake
open Lake DSL

package «umst-formal-double-slit» where

require mathlib from git
  "https://github.com/leanprover-community/mathlib4" @ "v4.14.0"

-- W-62: public CI checks out one repo; monorepo dev may override via `lakefile.lean.local` (untracked).
require «umst-formal» from git
  "https://github.com/tytolabs/umst-formal.git" @ "49e75238bfd1ee3b3b44c1297d80ed916b96a100" / "Lean"

/-!
  Self-contained quantum / measurement extension. Build:

  `cd Lean && lake build`

  **Default `roots`** = quantum + epistemic formal layer plus the vendored thermodynamic
  stack.  **Excluded on purpose:** `Test*.lean`, `test_tensor_eigen.lean`, optional
  `LogSum` / `MatrixLog`, `FlashMoERuntimeScaffold.lean`, etc.  Those files are not in
  `roots` so they do not run in default CI; build them explicitly (e.g. `lake build +TestEntropy`)
  when needed.  They have been manually grep-checked for `sorry` / stray `axiom`.

  **Lean root catalog (entries JSON):** From `Lean/`, run **`lake exe export_catalog`**
  to emit **`artifacts/catalog.json`** with `{ version, entries[{ id, module, kind, name }] }`.
  Details: **`tools/lean_export/README.md`**.

  **Python module scan (imports + digests):** **`make lean-catalog-export`** runs
  **`tools/lean_export/export_catalog.py`** — a different JSON shape for tooling that needs
  coarse import edges and per-file content hashes.
-/
-- LandauerLaw / LandauerExtension / LandauerEinsteinBridge come from the umst-formal
-- dependency @1bdd9ce (P0-1): wire `physicalSecondLaw` = `SecondLaw` predicate, zero local copies.
@[default_target]
lean_lib «UMST.DoubleSlit» where
  roots := #[`DensityState, `TensorPartialTrace, `MeasurementChannel, `DoubleSlitCore, `QuantumClassicalBridge,
    `InfoEntropy, `KroneckerEigen, `GeneralDimension, `LandauerBound, `EpistemicSensing, `EpistemicMI, `EpistemicDynamics,
    `EpistemicTrajectoryMI, `EpistemicPolicy, `EpistemicRuntimeContract, `EpistemicNumericsContract,
    `EpistemicPerStepNumerics, `EpistemicRuntimeSchemaContract, `EpistemicTelemetryBridge,
    `EpistemicTelemetryApproximation, `EpistemicTelemetryQuantitativeUtility,
    `EpistemicTraceDerivedEpsilonCertificate,
    `EpistemicTelemetrySolverCalibration, `EpistemicTraceDrivenCalibrationWitness,
    `PrototypeSolverCalibration, `GateCompat,
    `PMICEntropyInterior, `Complementarity, `PMICVisibility,
    `VonNeumannEntropy, `QuantumMutualInfo, `KleinInequality, `DataProcessingInequality,
    `DoubleSlit, `ProbeOptimization, `ExamplesQubit, `ExamplesQubitEpistemic, `ErasureChannel, `MeasurementCost,
    `KnowingFibreInstance,
    `EpistemicGalois, `SchrodingerDynamics, `LindbladDynamics, `LindbladStreamD, `DoubleSlitFormalWitness, `SimLeanBridge,
    -- LandauerExtension / LandauerEinsteinBridge / LandauerLaw: imported from umst-formal (not local roots)
    `GeneralResidualCoherence, `WhichPathMeasurementUpdate, `GeneralVisibility,
    `PhysicsConstrainedAI, `InformationCostIdentity, `LogSum, `MatrixLog, `FlashMoERuntimeScaffold]
    -- Optional / future: `MatrixLog, `LogSum (not in roots)
  srcDir := "."

/-!
  CHEM-NS-MVP-FORMAL-QUANTUM-DEFECT-CLEAR — SERIAL_ON_LAKEFILE quantum knowing fiber defect-clear wave.
  Sole writer for `ChemGeometry` lake targets during this SERIAL close. Build: `lake build ChemGeometry`.
  Honesty: measured census receipts; not physics GREEN.
  Knowing-fiber chemistry (`CHEM-FORMAL-Q-LEAN-CHEM`): Q-lattice electronic quantum numbers,
  SCALE ladder, EDGE-SURFACE sign convention.  `globs` auto-picks up future `Chem*.lean`;
  `ElementElectronic` stays an explicit root until renamed under `Chem*`.

  Build: `lake build ChemGeometry`
-/
@[default_target]
lean_lib ChemGeometry where
  roots := #[`ElementElectronic, `ChemGeometry, `AllotropeGeometry, `IsotopeBoundary, `ScaleCommute,
    `SurfaceBulkSdf]
  -- `Chem.+` glob activates when `Chem/` subtree exists (future geometry modules).
  srcDir := "."

/-!
  Knowing-fiber urge (`URGE-FORMAL-Q-LEAN-LANDAUER-HISTORY-LOOK`): Q-lattice epistemic
  Landauer history look; `globs` auto-picks up future `UrgeKnowing/*.lean`.

  Build: `lake build UrgeKnowing`
-/
/-!
  Ground states (`lake build Chem.GroundStates`): generated by scripts/gen_ground_states.py from the cited NIST data in
  chemistry/ground_states.json; the Madelung prediction, its laws, and the exception set decided by computation.
-/
@[default_target]
lean_lib «Chem.GroundStates» where
  roots := #[`Chem.GroundStates]
  srcDir := "."

@[default_target]
lean_lib UrgeKnowing where
  globs := #[`UrgeKnowing.+]
  srcDir := "."

/-- Emit `artifacts/catalog.json` (repo root): pinned Lake roots + schema; see `../tools/lean_export/README.md`. -/
lean_exe export_catalog where
  root := `ExportCatalog
  srcDir := "../tools/lean_export"
