-- SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
-- SPDX-License-Identifier: MIT

/-
-/

import Lake
open Lake DSL

package «umst-formal-double-slit» where

require mathlib from git
  "https://github.com/leanprover-community/mathlib4" @ "v4.14.0"

-- W-62: public CI checks out one repo; monorepo dev may override via `lakefile.lean.local` (untracked).
require «umst-formal» from git
  "https://github.com/tytolabs/umst-formal.git" @ "49e75238bfd1ee3b3b44c1297d80ed916b96a100" / "Lean"

/-!
  The knowing fibre: quantum states, measurement, epistemic information and their thermodynamic cost. Build:

  `cd Lean && lake build`

  Every tracked Lean file is compiled by a default target; scripts/check_lean_ci_closure.py fails when one is not.
  The second law (`UMST.ProcessFamily.SecondLaw`), the Landauer law and the SI constants come from the umst-formal
  dependency above; this package adds no law of its own.

  The module catalog (`artifacts/catalog.json`, `artifacts/catalog.lock.json`) is written by one tool,
  `make lean-catalog-export` (`tools/lean_export/export_catalog.py`).
-/
@[default_target]
lean_lib «UMST.DoubleSlit» where
  roots := #[`DensityState, `TensorPartialTrace, `MeasurementChannel, `DoubleSlitCore, `QuantumClassicalBridge,
    `InfoEntropy, `KroneckerEigen, `GeneralDimension, `LandauerBound, `EpistemicSensing, `EpistemicMI, `EpistemicDynamics,
    `EpistemicTrajectoryMI, `EpistemicPolicy, `EpistemicRuntimeContract, `EpistemicNumericsContract,
    `EpistemicPerStepNumerics, `EpistemicRuntimeSchemaContract, `EpistemicTelemetryBridge,
    `EpistemicTelemetryApproximation, `EpistemicTelemetryQuantitativeUtility,
    `EpistemicTraceDerivedEpsilonCertificate,
    `EpistemicTelemetrySolverCalibration, `EpistemicTraceDrivenCalibrationWitness,
    `PrototypeSolverCalibration, `GateCompat,
    `PMICEntropyInterior, `PMICVisibility,
    `VonNeumannEntropy, `QuantumMutualInfo, `KleinInequality, `DataProcessingInequality,
    `DoubleSlit, `ProbeOptimization, `ExamplesQubit, `ExamplesQubitEpistemic, `ErasureChannel, `MeasurementCost,
    `KnowingFibreInstance, `CompressionCost,
    `EpistemicGalois, `SchrodingerDynamics, `LindbladDynamics, `LindbladStreamD, `DoubleSlitFormalWitness, `SimLeanBridge,
    -- LandauerExtension / LandauerEinsteinBridge / LandauerLaw: imported from umst-formal (not local roots)
    `GeneralResidualCoherence, `WhichPathMeasurementUpdate, `GeneralVisibility,
    `InformationCostIdentity, `LogSum, `MatrixLog]
  srcDir := "."

/-!
  Ground states (`lake build Chem.GroundStates`): generated by scripts/gen_ground_states.py from the cited NIST data in
  chemistry/ground_states.json; the subshell and shell capacities derived from the one-electron states, the Madelung
  prediction, its laws, and the exception set decided by computation.
-/
@[default_target]
lean_lib «Chem.GroundStates» where
  roots := #[`Chem.GroundStates]
  srcDir := "."
