/-
SPDX-License-Identifier: MIT
Copyright (c) 2026 Santhosh Shyamsundar, Santosh Prabhu Shenbagamoorthy — Studio TYTO

Aggregator module: imports every root of the UMST.DoubleSlit lean_lib.
Used by lean4checker in CI so all oleans are transitively replayed via a
single, stable module name (`UMSTAll`).
-/

import UMSTCore
import DensityState
import TensorPartialTrace
import MeasurementChannel
import DoubleSlitCore
import QuantumClassicalBridge
import InfoEntropy
import GeneralDimension
import LandauerBound
import EpistemicSensing
import EpistemicMI
import EpistemicDynamics
import EpistemicTrajectoryMI
import EpistemicPolicy
import EpistemicRuntimeContract
import EpistemicNumericsContract
import EpistemicPerStepNumerics
import EpistemicRuntimeSchemaContract
import EpistemicTelemetryBridge
import EpistemicTelemetryApproximation
import EpistemicTelemetryQuantitativeUtility
import EpistemicTraceDerivedEpsilonCertificate
import EpistemicTelemetrySolverCalibration
import EpistemicTraceDrivenCalibrationWitness
import PrototypeSolverCalibration
import GateCompat
import QRBridge
import PMICEntropyInterior
import Complementarity
import PMICVisibility
import VonNeumannEntropy
import QuantumMutualInfo
import DataProcessingInequality
import DoubleSlit
import ProbeOptimization
import ExamplesQubit
import ErasureChannel
import MeasurementCost
import EpistemicGalois
import SchrodingerDynamics
import LindbladDynamics
import SimLeanBridge
import LandauerLaw
import LandauerExtension
import LandauerEinsteinBridge
import Gate
import Naturality
import Activation
import FiberedActivation
import MonoidalState
import GeneralResidualCoherence
import WhichPathMeasurementUpdate
import GeneralVisibility
